--[[
  dummy

  dummy

  The version of the OpenAPI document: dummy
  
  Generated by: https://openapi-generator.tech
]]

-- dummy_200_response_outer_prop class
local dummy_200_response_outer_prop = {}
local dummy_200_response_outer_prop_mt = {
	__name = "dummy_200_response_outer_prop";
	__index = dummy_200_response_outer_prop;
}

local function cast_dummy_200_response_outer_prop(t)
	return setmetatable(t, dummy_200_response_outer_prop_mt)
end

local function new_dummy_200_response_outer_prop(inner_prop)
	return cast_dummy_200_response_outer_prop({
		["innerProp"] = inner_prop;
	})
end

return {
	cast = cast_dummy_200_response_outer_prop;
	new = new_dummy_200_response_outer_prop;
}
