--[[
  dummy

  dummy

  The version of the OpenAPI document: dummy
  
  Generated by: https://openapi-generator.tech
]]

-- dummy_200_response class
local dummy_200_response = {}
local dummy_200_response_mt = {
	__name = "dummy_200_response";
	__index = dummy_200_response;
}

local function cast_dummy_200_response(t)
	return setmetatable(t, dummy_200_response_mt)
end

local function new_dummy_200_response(outer_prop)
	return cast_dummy_200_response({
		["outerProp"] = outer_prop;
	})
end

return {
	cast = cast_dummy_200_response;
	new = new_dummy_200_response;
}
