--[[
  dummy

  dummy

  The version of the OpenAPI document: dummy
  
  Generated by: https://openapi-generator.tech
]]

-- other_object class
local other_object = {}
local other_object_mt = {
	__name = "other_object";
	__index = other_object;
}

local function cast_other_object(t)
	return setmetatable(t, other_object_mt)
end

local function new_other_object(my_only_property2)
	return cast_other_object({
		["myOnlyProperty2"] = my_only_property2;
	})
end

return {
	cast = cast_other_object;
	new = new_other_object;
}
