/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.api;

import org.openapitools.client.ApiResponse;
import org.openapitools.client.model.ExampleResponse;

/**
 * 
 *
 * <p>No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 */
public interface DefaultApi {

  ApiResponse<ExampleResponse> exampleSomeMethodGet();

}
