/*
 * dummy
 *
 * dummy
 *
 * The version of the OpenAPI document: dummy
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dummy200ResponseOuterPropInnerProp {
    #[serde(rename = "myBool", skip_serializing_if = "Option::is_none")]
    pub my_bool: Option<bool>,
}

impl Dummy200ResponseOuterPropInnerProp {
    pub fn new() -> Dummy200ResponseOuterPropInnerProp {
        Dummy200ResponseOuterPropInnerProp {
            my_bool: None,
        }
    }
}


