/*
 * Some example
 *
 * dummy description
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ExampleResponse {
    #[serde(rename = "myOnlyProperty", skip_serializing_if = "Option::is_none")]
    pub my_only_property: Option<Vec<bool>>,
}

impl ExampleResponse {
    pub fn new() -> ExampleResponse {
        ExampleResponse {
            my_only_property: None,
        }
    }
}


