/**
 * dummy
 * dummy
 *
 * OpenAPI spec version: dummy
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIDummy200ResponseOuterPropInnerProp.h"

#include "OpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

void OpenAPIDummy200ResponseOuterPropInnerProp::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (MyBool.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("myBool")); WriteJsonValue(Writer, MyBool.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool OpenAPIDummy200ResponseOuterPropInnerProp::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("myBool"), MyBool);

	return ParseSuccess;
}

}
