/**
 * dummy
 * dummy
 *
 * OpenAPI spec version: dummy
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIOtherObject.h"

#include "OpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

void OpenAPIOtherObject::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (MyOnlyProperty2.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("myOnlyProperty2")); WriteJsonValue(Writer, MyOnlyProperty2.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool OpenAPIOtherObject::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("myOnlyProperty2"), MyOnlyProperty2);

	return ParseSuccess;
}

}
