/**
 * 
 * dummy description
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIExampleResponse.h"

#include "OpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

void OpenAPIExampleResponse::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (MyOnlyProperty.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("myOnlyProperty")); WriteJsonValue(Writer, MyOnlyProperty.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool OpenAPIExampleResponse::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("myOnlyProperty"), MyOnlyProperty);

	return ParseSuccess;
}

}
