/*
 * dummy
 *
 * dummy
 *
 * API version: dummy
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package petstoreserver


import (
	"encoding/json"
)



// ExampleResponse - dummy
type ExampleResponse struct {

	EmptyString string `json:"emptyString,omitempty"`

	NumberString string `json:"numberString,omitempty"`

	BoolString string `json:"boolString,omitempty"`

	NullString string `json:"nullString,omitempty"`

	ABool bool `json:"aBool,omitempty"`

	Zero int32 `json:"zero,omitempty"`
}

// UnmarshalJSON sets *m to a copy of data while respecting defaults if specified.
func (m *ExampleResponse) UnmarshalJSON(data []byte) error {
	m.EmptyString = ""
	m.NumberString = "42"
	m.BoolString = "false"
	m.NullString = "null"
	m.ABool = false
	m.Zero = 0

	type Alias ExampleResponse // To avoid infinite recursion
    return json.Unmarshal(data, (*Alias)(m))
}

// AssertExampleResponseRequired checks if the required fields are not zero-ed
func AssertExampleResponseRequired(obj ExampleResponse) error {
	return nil
}

// AssertExampleResponseConstraints checks if the values respects the defined constraints
func AssertExampleResponseConstraints(obj ExampleResponse) error {
	return nil
}
