=begin
#dummy

#dummy

The version of the OpenAPI document: dummy

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for XAuthIDAlias::Dummy200ResponseOuterPropInnerProp
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe XAuthIDAlias::Dummy200ResponseOuterPropInnerProp do
  let(:instance) { XAuthIDAlias::Dummy200ResponseOuterPropInnerProp.new }

  describe 'test an instance of Dummy200ResponseOuterPropInnerProp' do
    it 'should create an instance of Dummy200ResponseOuterPropInnerProp' do
      expect(instance).to be_instance_of(XAuthIDAlias::Dummy200ResponseOuterPropInnerProp)
    end
  end
  describe 'test attribute "my_bool"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
