=begin
#

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for XAuthIDAlias::ExampleResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe XAuthIDAlias::ExampleResponse do
  let(:instance) { XAuthIDAlias::ExampleResponse.new }

  describe 'test an instance of ExampleResponse' do
    it 'should create an instance of ExampleResponse' do
      expect(instance).to be_instance_of(XAuthIDAlias::ExampleResponse)
    end
  end
  describe 'test attribute "my_only_property"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
