/**
 * dummy
 * dummy
 *
 * OpenAPI spec version: dummy
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ExampleResponse } from '../models/ExampleResponse';
import { HttpFile } from '../http/http';

/**
* dummy
*/
export class OtherObject {
    'myOnlyProperty2'?: ExampleResponse;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "myOnlyProperty2",
            "baseName": "myOnlyProperty2",
            "type": "ExampleResponse",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OtherObject.attributeTypeMap;
    }

    public constructor() {
    }
}

