/*
dummy

dummy

API version: dummy
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package petstore

import (
	"encoding/json"
)

// checks if the Dummy200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Dummy200Response{}

// Dummy200Response struct for Dummy200Response
type Dummy200Response struct {
	OuterProp *Dummy200ResponseOuterProp `json:"outerProp,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Dummy200Response Dummy200Response

// NewDummy200Response instantiates a new Dummy200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDummy200Response() *Dummy200Response {
	this := Dummy200Response{}
	return &this
}

// NewDummy200ResponseWithDefaults instantiates a new Dummy200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDummy200ResponseWithDefaults() *Dummy200Response {
	this := Dummy200Response{}
	return &this
}

// GetOuterProp returns the OuterProp field value if set, zero value otherwise.
func (o *Dummy200Response) GetOuterProp() Dummy200ResponseOuterProp {
	if o == nil || IsNil(o.OuterProp) {
		var ret Dummy200ResponseOuterProp
		return ret
	}
	return *o.OuterProp
}

// GetOuterPropOk returns a tuple with the OuterProp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dummy200Response) GetOuterPropOk() (*Dummy200ResponseOuterProp, bool) {
	if o == nil || IsNil(o.OuterProp) {
		return nil, false
	}
	return o.OuterProp, true
}

// HasOuterProp returns a boolean if a field has been set.
func (o *Dummy200Response) HasOuterProp() bool {
	if o != nil && !IsNil(o.OuterProp) {
		return true
	}

	return false
}

// SetOuterProp gets a reference to the given Dummy200ResponseOuterProp and assigns it to the OuterProp field.
func (o *Dummy200Response) SetOuterProp(v Dummy200ResponseOuterProp) {
	o.OuterProp = &v
}

func (o Dummy200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Dummy200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OuterProp) {
		toSerialize["outerProp"] = o.OuterProp
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Dummy200Response) UnmarshalJSON(bytes []byte) (err error) {
	varDummy200Response := _Dummy200Response{}

	if err = json.Unmarshal(bytes, &varDummy200Response); err == nil {
		*o = Dummy200Response(varDummy200Response)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "outerProp")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDummy200Response struct {
	value *Dummy200Response
	isSet bool
}

func (v NullableDummy200Response) Get() *Dummy200Response {
	return v.value
}

func (v *NullableDummy200Response) Set(val *Dummy200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDummy200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDummy200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDummy200Response(val *Dummy200Response) *NullableDummy200Response {
	return &NullableDummy200Response{value: val, isSet: true}
}

func (v NullableDummy200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDummy200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


