{-
   dummy

   dummy

   OpenAPI Version: 3.0.0
   dummy API version: dummy
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : Dummy.Lens
-}

{-# LANGUAGE KindSignatures #-}
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE RecordWildCards #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-matches -fno-warn-unused-binds -fno-warn-unused-imports #-}

module Dummy.ModelLens where

import qualified Data.Aeson as A
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Data, Typeable)
import qualified Data.Map as Map
import qualified Data.Set as Set
import qualified Data.Time as TI

import Data.Text (Text)

import Prelude (($), (.),(<$>),(<*>),(=<<),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

import Dummy.Model
import Dummy.Core


-- * Dummy200Response

-- | 'dummy200ResponseOuterProp' Lens
dummy200ResponseOuterPropL :: Lens_' Dummy200Response (Maybe Dummy200ResponseOuterProp)
dummy200ResponseOuterPropL f Dummy200Response{..} = (\dummy200ResponseOuterProp -> Dummy200Response { dummy200ResponseOuterProp, ..} ) <$> f dummy200ResponseOuterProp
{-# INLINE dummy200ResponseOuterPropL #-}



-- * Dummy200ResponseOuterProp

-- | 'dummy200ResponseOuterPropInnerProp' Lens
dummy200ResponseOuterPropInnerPropL :: Lens_' Dummy200ResponseOuterProp (Maybe Dummy200ResponseOuterPropInnerProp)
dummy200ResponseOuterPropInnerPropL f Dummy200ResponseOuterProp{..} = (\dummy200ResponseOuterPropInnerProp -> Dummy200ResponseOuterProp { dummy200ResponseOuterPropInnerProp, ..} ) <$> f dummy200ResponseOuterPropInnerProp
{-# INLINE dummy200ResponseOuterPropInnerPropL #-}



-- * Dummy200ResponseOuterPropInnerProp

-- | 'dummy200ResponseOuterPropInnerPropMyBool' Lens
dummy200ResponseOuterPropInnerPropMyBoolL :: Lens_' Dummy200ResponseOuterPropInnerProp (Maybe Bool)
dummy200ResponseOuterPropInnerPropMyBoolL f Dummy200ResponseOuterPropInnerProp{..} = (\dummy200ResponseOuterPropInnerPropMyBool -> Dummy200ResponseOuterPropInnerProp { dummy200ResponseOuterPropInnerPropMyBool, ..} ) <$> f dummy200ResponseOuterPropInnerPropMyBool
{-# INLINE dummy200ResponseOuterPropInnerPropMyBoolL #-}


