// tslint:disable
/**
 * dummy
 * dummy
 *
 * The version of the OpenAPI document: dummy
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    OtherObject,
} from './';

/**
 * dummy
 * @export
 * @interface ExampleResponse
 */
export interface ExampleResponse {
    /**
     * @type {OtherObject}
     * @memberof ExampleResponse
     */
    myOnlyProperty?: OtherObject;
}
