/*
dummy

dummy

API version: dummy
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package x_auth_id_alias

import (
	"encoding/json"
)

// checks if the Dummy200ResponseOuterPropInnerProp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Dummy200ResponseOuterPropInnerProp{}

// Dummy200ResponseOuterPropInnerProp struct for Dummy200ResponseOuterPropInnerProp
type Dummy200ResponseOuterPropInnerProp struct {
	MyBool *bool `json:"myBool,omitempty"`
}

// NewDummy200ResponseOuterPropInnerProp instantiates a new Dummy200ResponseOuterPropInnerProp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDummy200ResponseOuterPropInnerProp() *Dummy200ResponseOuterPropInnerProp {
	this := Dummy200ResponseOuterPropInnerProp{}
	return &this
}

// NewDummy200ResponseOuterPropInnerPropWithDefaults instantiates a new Dummy200ResponseOuterPropInnerProp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDummy200ResponseOuterPropInnerPropWithDefaults() *Dummy200ResponseOuterPropInnerProp {
	this := Dummy200ResponseOuterPropInnerProp{}
	return &this
}

// GetMyBool returns the MyBool field value if set, zero value otherwise.
func (o *Dummy200ResponseOuterPropInnerProp) GetMyBool() bool {
	if o == nil || IsNil(o.MyBool) {
		var ret bool
		return ret
	}
	return *o.MyBool
}

// GetMyBoolOk returns a tuple with the MyBool field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Dummy200ResponseOuterPropInnerProp) GetMyBoolOk() (*bool, bool) {
	if o == nil || IsNil(o.MyBool) {
		return nil, false
	}
	return o.MyBool, true
}

// HasMyBool returns a boolean if a field has been set.
func (o *Dummy200ResponseOuterPropInnerProp) HasMyBool() bool {
	if o != nil && !IsNil(o.MyBool) {
		return true
	}

	return false
}

// SetMyBool gets a reference to the given bool and assigns it to the MyBool field.
func (o *Dummy200ResponseOuterPropInnerProp) SetMyBool(v bool) {
	o.MyBool = &v
}

func (o Dummy200ResponseOuterPropInnerProp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Dummy200ResponseOuterPropInnerProp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MyBool) {
		toSerialize["myBool"] = o.MyBool
	}
	return toSerialize, nil
}

type NullableDummy200ResponseOuterPropInnerProp struct {
	value *Dummy200ResponseOuterPropInnerProp
	isSet bool
}

func (v NullableDummy200ResponseOuterPropInnerProp) Get() *Dummy200ResponseOuterPropInnerProp {
	return v.value
}

func (v *NullableDummy200ResponseOuterPropInnerProp) Set(val *Dummy200ResponseOuterPropInnerProp) {
	v.value = val
	v.isSet = true
}

func (v NullableDummy200ResponseOuterPropInnerProp) IsSet() bool {
	return v.isSet
}

func (v *NullableDummy200ResponseOuterPropInnerProp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDummy200ResponseOuterPropInnerProp(val *Dummy200ResponseOuterPropInnerProp) *NullableDummy200ResponseOuterPropInnerProp {
	return &NullableDummy200ResponseOuterPropInnerProp{value: val, isSet: true}
}

func (v NullableDummy200ResponseOuterPropInnerProp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDummy200ResponseOuterPropInnerProp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


