=begin
#Some example

#dummy description

The version of the OpenAPI document: 0.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.0-SNAPSHOT

=end

# Common files
require 'dynamic_servers/api_client'
require 'dynamic_servers/api_error'
require 'dynamic_servers/version'
require 'dynamic_servers/configuration'

# Models
require 'dynamic_servers/models/example_response'

# APIs
require 'dynamic_servers/api/default_api'

module DynamicServers
  class << self
    # Customize default settings for the SDK using block.
    #   DynamicServers.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
