#
# Some example
# 
# dummy description
# The version of the OpenAPI document: 0.0.1
# 
# Generated by: https://openapi-generator.tech
#

import httpclient
import logging
import options

import petstore

import config

let logger = newConsoleLogger()
addHandler(logger)

let client = newHttpClient()
client.headers["User-Agent"] = config.useragent
