/*
 * dummy
 * dummy
 *
 * The version of the OpenAPI document: dummy
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonTypeName;
import org.openapitools.model.Dummy200ResponseOuterProp;
import com.fasterxml.jackson.annotation.*;

import javax.validation.constraints.*;
import javax.validation.Valid;
import io.micronaut.core.annotation.*;
import javax.annotation.Generated;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Dummy200Response
 */
@JsonPropertyOrder({
  Dummy200Response.JSON_PROPERTY_OUTER_PROP
})
@JsonTypeName("dummy_200_response")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautServerCodegen")
@Introspected
public class Dummy200Response {
    public static final String JSON_PROPERTY_OUTER_PROP = "outerProp";
    private Dummy200ResponseOuterProp outerProp;

    public Dummy200Response() {
    }

    public Dummy200Response outerProp(Dummy200ResponseOuterProp outerProp) {
        this.outerProp = outerProp;
        return this;
    }

    /**
     * Get outerProp
     * @return outerProp
     **/
    @Valid
    @Nullable
    @Schema(name = "outerProp", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty(JSON_PROPERTY_OUTER_PROP)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Dummy200ResponseOuterProp getOuterProp() {
        return outerProp;
    }

    @JsonProperty(JSON_PROPERTY_OUTER_PROP)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setOuterProp(Dummy200ResponseOuterProp outerProp) {
        this.outerProp = outerProp;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Dummy200Response dummy200Response = (Dummy200Response) o;
        return Objects.equals(this.outerProp, dummy200Response.outerProp);
    }

    @Override
    public int hashCode() {
        return Objects.hash(outerProp);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Dummy200Response {\n");
        sb.append("    outerProp: ").append(toIndentedString(outerProp)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

