/*
 * dummy
 * dummy
 *
 * The version of the OpenAPI document: dummy
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonTypeName;
import org.openapitools.model.Dummy200ResponseOuterPropInnerProp;
import com.fasterxml.jackson.annotation.*;

import javax.validation.constraints.*;
import javax.validation.Valid;
import io.micronaut.core.annotation.*;
import javax.annotation.Generated;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Dummy200ResponseOuterProp
 */
@JsonPropertyOrder({
  Dummy200ResponseOuterProp.JSON_PROPERTY_INNER_PROP
})
@JsonTypeName("dummy_200_response_outerProp")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautServerCodegen")
@Introspected
public class Dummy200ResponseOuterProp {
    public static final String JSON_PROPERTY_INNER_PROP = "innerProp";
    private Dummy200ResponseOuterPropInnerProp innerProp;

    public Dummy200ResponseOuterProp() {
    }

    public Dummy200ResponseOuterProp innerProp(Dummy200ResponseOuterPropInnerProp innerProp) {
        this.innerProp = innerProp;
        return this;
    }

    /**
     * Get innerProp
     * @return innerProp
     **/
    @Valid
    @Nullable
    @Schema(name = "innerProp", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty(JSON_PROPERTY_INNER_PROP)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Dummy200ResponseOuterPropInnerProp getInnerProp() {
        return innerProp;
    }

    @JsonProperty(JSON_PROPERTY_INNER_PROP)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setInnerProp(Dummy200ResponseOuterPropInnerProp innerProp) {
        this.innerProp = innerProp;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Dummy200ResponseOuterProp dummy200ResponseOuterProp = (Dummy200ResponseOuterProp) o;
        return Objects.equals(this.innerProp, dummy200ResponseOuterProp.innerProp);
    }

    @Override
    public int hashCode() {
        return Objects.hash(innerProp);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Dummy200ResponseOuterProp {\n");
        sb.append("    innerProp: ").append(toIndentedString(innerProp)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

