/*
 * dummy
 * dummy
 *
 * The version of the OpenAPI document: dumy
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.math.BigDecimal;
import java.util.LinkedHashSet;
import java.util.Set;
import com.fasterxml.jackson.annotation.*;

import javax.validation.constraints.*;
import javax.validation.Valid;
import io.micronaut.core.annotation.*;
import javax.annotation.Generated;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * dummy
 */
@Schema(name = "ExampleResponse", description = "dummy")
@JsonPropertyOrder({
  ExampleResponse.JSON_PROPERTY_MY_ONLY_PROPERTY
})
@JsonTypeName("ExampleResponse")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautServerCodegen")
@Introspected
public class ExampleResponse {
    public static final String JSON_PROPERTY_MY_ONLY_PROPERTY = "myOnlyProperty";
    private Set<BigDecimal> myOnlyProperty = null;

    public ExampleResponse() {
    }

    public ExampleResponse myOnlyProperty(Set<BigDecimal> myOnlyProperty) {
        this.myOnlyProperty = myOnlyProperty;
        return this;
    }

    public ExampleResponse addMyOnlyPropertyItem(BigDecimal myOnlyPropertyItem) {
        if (this.myOnlyProperty == null) {
            this.myOnlyProperty = new LinkedHashSet<>();
        }
        this.myOnlyProperty.add(myOnlyPropertyItem);
        return this;
    }

    /**
     * Get myOnlyProperty
     * @return myOnlyProperty
     **/
    @Nullable
    @Schema(name = "myOnlyProperty", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty(JSON_PROPERTY_MY_ONLY_PROPERTY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Set<BigDecimal> getMyOnlyProperty() {
        return myOnlyProperty;
    }

    @JsonProperty(JSON_PROPERTY_MY_ONLY_PROPERTY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
       @JsonDeserialize(as = LinkedHashSet.class)
    public void setMyOnlyProperty(Set<BigDecimal> myOnlyProperty) {
        this.myOnlyProperty = myOnlyProperty;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ExampleResponse exampleResponse = (ExampleResponse) o;
        return Objects.equals(this.myOnlyProperty, exampleResponse.myOnlyProperty);
    }

    @Override
    public int hashCode() {
        return Objects.hash(myOnlyProperty);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ExampleResponse {\n");
        sb.append("    myOnlyProperty: ").append(toIndentedString(myOnlyProperty)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

