/*
 * dummy
 * dummy
 *
 * The version of the OpenAPI document: dummy
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.model;

import java.util.Objects;
import java.util.Arrays;
import org.openapitools.model.ExampleResponse;
import com.fasterxml.jackson.annotation.*;

import javax.validation.constraints.*;
import javax.validation.Valid;
import io.micronaut.core.annotation.*;
import javax.annotation.Generated;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * dummy
 */
@Schema(name = "OtherObject", description = "dummy")
@JsonPropertyOrder({
  OtherObject.JSON_PROPERTY_MY_ONLY_PROPERTY2
})
@JsonTypeName("OtherObject")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautServerCodegen")
@Introspected
public class OtherObject {
    public static final String JSON_PROPERTY_MY_ONLY_PROPERTY2 = "myOnlyProperty2";
    private ExampleResponse myOnlyProperty2;

    public OtherObject() {
    }

    public OtherObject myOnlyProperty2(ExampleResponse myOnlyProperty2) {
        this.myOnlyProperty2 = myOnlyProperty2;
        return this;
    }

    /**
     * Get myOnlyProperty2
     * @return myOnlyProperty2
     **/
    @Valid
    @Nullable
    @Schema(name = "myOnlyProperty2", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty(JSON_PROPERTY_MY_ONLY_PROPERTY2)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public ExampleResponse getMyOnlyProperty2() {
        return myOnlyProperty2;
    }

    @JsonProperty(JSON_PROPERTY_MY_ONLY_PROPERTY2)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMyOnlyProperty2(ExampleResponse myOnlyProperty2) {
        this.myOnlyProperty2 = myOnlyProperty2;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OtherObject otherObject = (OtherObject) o;
        return Objects.equals(this.myOnlyProperty2, otherObject.myOnlyProperty2);
    }

    @Override
    public int hashCode() {
        return Objects.hash(myOnlyProperty2);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class OtherObject {\n");
        sb.append("    myOnlyProperty2: ").append(toIndentedString(myOnlyProperty2)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

