# coding: utf-8

"""
    

    dummy description

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI

from openapi_server.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="",
    description="dummy description",
    version="",
)

app.include_router(DefaultApiRouter)
