#import <Foundation/Foundation.h>
#import <JSONModel/JSONValueTransformer.h>

/**
* 
* dummy description
*
* The version of the OpenAPI document: 
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


@interface JSONValueTransformer (ISO8601)

@end
