/*
 * dummy
 * dummy
 *
 * OpenAPI spec version: dummy
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://github.com/OpenAPITools/openapi-generator
 *
 * OpenAPI generator version: 7.0.0-SNAPSHOT
 */


import http from "k6/http";
import { group, check, sleep } from "k6";

const BASE_URL = "/";
// Sleep duration between successive requests.
// You might want to edit the value of this variable or remove calls to the sleep function on the script.
const SLEEP_DURATION = 0.1;
// Global variables should be initialized.

export default function() {
    group("/example/someMethod", () => {

        // Request No. 1: dummy
        {
            let url = BASE_URL + `/example/someMethod`;
            let request = http.get(url);

            check(request, {
                "dummy": (r) => r.status === 201
            });
            check(request, {
                "dummy": (r) => r.status === 200
            });
        }
    });

}
