# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Dummy200ResponseOuterPropInnerProp(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, my_bool: bool=None):
        """Dummy200ResponseOuterPropInnerProp - a model defined in OpenAPI

        :param my_bool: The my_bool of this Dummy200ResponseOuterPropInnerProp.
        """
        self.openapi_types = {
            'my_bool': bool
        }

        self.attribute_map = {
            'my_bool': 'myBool'
        }

        self._my_bool = my_bool

    @classmethod
    def from_dict(cls, dikt: dict) -> 'Dummy200ResponseOuterPropInnerProp':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The dummy_200_response_outerProp_innerProp of this Dummy200ResponseOuterPropInnerProp.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def my_bool(self):
        """Gets the my_bool of this Dummy200ResponseOuterPropInnerProp.


        :return: The my_bool of this Dummy200ResponseOuterPropInnerProp.
        :rtype: bool
        """
        return self._my_bool

    @my_bool.setter
    def my_bool(self, my_bool):
        """Sets the my_bool of this Dummy200ResponseOuterPropInnerProp.


        :param my_bool: The my_bool of this Dummy200ResponseOuterPropInnerProp.
        :type my_bool: bool
        """

        self._my_bool = my_bool
