# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server.models.dummy200_response_outer_prop import Dummy200ResponseOuterProp
from openapi_server import util


class Dummy200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, outer_prop: Dummy200ResponseOuterProp=None):
        """Dummy200Response - a model defined in OpenAPI

        :param outer_prop: The outer_prop of this Dummy200Response.
        """
        self.openapi_types = {
            'outer_prop': Dummy200ResponseOuterProp
        }

        self.attribute_map = {
            'outer_prop': 'outerProp'
        }

        self._outer_prop = outer_prop

    @classmethod
    def from_dict(cls, dikt: dict) -> 'Dummy200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The dummy_200_response of this Dummy200Response.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def outer_prop(self):
        """Gets the outer_prop of this Dummy200Response.


        :return: The outer_prop of this Dummy200Response.
        :rtype: Dummy200ResponseOuterProp
        """
        return self._outer_prop

    @outer_prop.setter
    def outer_prop(self, outer_prop):
        """Sets the outer_prop of this Dummy200Response.


        :param outer_prop: The outer_prop of this Dummy200Response.
        :type outer_prop: Dummy200ResponseOuterProp
        """

        self._outer_prop = outer_prop
