--[[
  

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 
  
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for petstore.api.default_api
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("default_api", function()
  local petstore_default_api = require "petstore.api.default_api"
  -- unit tests for example_some_method_get
  describe("example_some_method_get test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
