--[[
  Some example

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 0.0.1
  
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for petstore.model.example_response
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("example_response", function()
  local petstore_example_response = require "petstore.model.example_response"

  -- unit tests for the property 'my_only_property'
  describe("property my_only_property test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
