# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

module PetStoreClient

using Dates, TimeZones
using OpenAPI
using OpenAPI.Clients

const API_VERSION = "dumy"

include("modelincludes.jl")

include("apis/api_DefaultApi.jl")

end # module PetStoreClient
