# coding: utf-8

# flake8: noqa
"""
    dummy

    dummy  # noqa: E501

    The version of the OpenAPI document: dummy
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


# import models into model package
from petstore_api.models.dummy200_response import Dummy200Response
from petstore_api.models.dummy200_response_outer_prop import Dummy200ResponseOuterProp
from petstore_api.models.dummy200_response_outer_prop_inner_prop import Dummy200ResponseOuterPropInnerProp
from petstore_api.models.example_response import ExampleResponse
from petstore_api.models.node import Node
from petstore_api.models.other_object import OtherObject
