/*
 * 
 *
 * dummy description
 *
 * API version: 
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package petstoreserver

type ExampleResponse struct {

	MyOnlyProperty []bool `json:"myOnlyProperty,omitempty"`
}
