/**
* dummy
* dummy
*
* The version of the OpenAPI document: dummy
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.database.models

import org.ktorm.dsl.*
import org.ktorm.schema.*
import org.ktorm.database.Database
import org.openapitools.client.models.*


/**
 * 
 * @param innerProp 
 */
object Dummy200ResponseOuterProps : BaseTable<Dummy200ResponseOuterProp>("dummy_200_response_outerProp") {
    val innerProp = long("innerProp") /* null */

    /**
     * Create an entity of type Dummy200ResponseOuterProp from the model
     */
    override fun doCreateEntity(row: QueryRowSet, withReferences: Boolean) = Dummy200ResponseOuterProp(
        innerProp = Dummy200ResponseOuterPropInnerProps.createEntity(row, withReferences) /* Dummy200ResponseOuterPropInnerProp? */
    )

    /**
    * Assign all the columns from the entity of type Dummy200ResponseOuterProp to the DML expression.
    *
    * Usage:
    *
    * ```kotlin
    * let entity = Dummy200ResponseOuterProp()
    * database.update(Dummy200ResponseOuterProps, {
    *     assignFrom(entity)
    * })
    * ```
    * @return the builder with the columns for the update or insert.
    */
    fun AssignmentsBuilder.assignFrom(entity: Dummy200ResponseOuterProp) {
        this.apply {
            set(Dummy200ResponseOuterProps.innerProp, entity.innerProp)
        }
    }

}


