/**
* 
* dummy description
*
* The version of the OpenAPI document: 
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.database.models

import org.ktorm.dsl.*
import org.ktorm.schema.*
import org.ktorm.database.Database
import org.openapitools.client.models.*


/**
 * 
 * @param myOnlyProperty 
 */
object ExampleResponses : BaseTable<ExampleResponse>("ExampleResponse") {

    /**
     * Create an entity of type ExampleResponse from the model
     */
    override fun doCreateEntity(row: QueryRowSet, withReferences: Boolean) = ExampleResponse(
        myOnlyProperty = emptyList() /* kotlin.Array<kotlin.Boolean>? */
    )

    /**
    * Assign all the columns from the entity of type ExampleResponse to the DML expression.
    *
    * Usage:
    *
    * ```kotlin
    * let entity = ExampleResponse()
    * database.update(ExampleResponses, {
    *     assignFrom(entity)
    * })
    * ```
    * @return the builder with the columns for the update or insert.
    */
    fun AssignmentsBuilder.assignFrom(entity: ExampleResponse) {
        this.apply {
        }
    }

}


object ExampleResponseMyOnlyProperty : BaseTable<Pair<kotlin.Long, kotlin.Boolean>>("ExampleResponseMyOnlyProperty") {
    val exampleResponse = long("exampleResponse")
    val myOnlyProperty = boolean("myOnlyProperty")

    override fun doCreateEntity(row: QueryRowSet, withReferences: Boolean): Pair<kotlin.Long, kotlin.Boolean> =
        Pair(row[exampleResponse] ?: 0, row[myOnlyProperty] ?: 0)

    fun AssignmentsBuilder.assignFrom(entity: Pair<kotlin.Long, kotlin.Boolean>) {
        this.apply {
            set(ExampleResponseMyOnlyProperty.exampleResponse, entity.first)
            set(ExampleResponseMyOnlyProperty.myOnlyProperty, entity.second)
        }
    }

}

