/**
 * dummy
 * dummy
 *
 * The version of the OpenAPI document: dummy
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Dummy200Response {
  outerProp?: Dummy200ResponseOuterProp;
}


export interface Dummy200ResponseOuterProp {
  innerProp?: Dummy200ResponseOuterPropInnerProp;
}


export interface Dummy200ResponseOuterPropInnerProp {
  myBool?: boolean;
}


/**
 * dummy
 */
export interface ExampleResponse {
  myOnlyProperty?: OtherObject;
}


/**
 * dummy
 */
export interface Node {
  left?: Node;
  right?: Node;
}


/**
 * dummy
 */
export interface OtherObject {
  myOnlyProperty2?: ExampleResponse;
}

