# coding: utf-8

# flake8: noqa
"""
    

    dummy description  # noqa: E501

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


# import models into model package
from petstore_api.models.example_response import ExampleResponse
