openapi: 3.0.0
info:
  description: dummy
  title: dummy
  version: dumy
servers:
- url: /
paths:
  /example/someMethod:
    get:
      description: dummy
      operationId: dummy
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ExampleResponse'
          description: dummy
      x-accepts: '*/*'
components:
  schemas:
    ExampleResponse:
      description: dummy
      example:
        myOnlyProperty:
        - 0.8008281904610115
        - 0.8008281904610115
      properties:
        myOnlyProperty:
          items:
            type: number
          type: array
          uniqueItems: true
      type: object

