<?php
/**
 * Dummy200ResponseOuterProp
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * dummy
 *
 * dummy
 *
 * The version of the OpenAPI document: dummy
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Dummy200ResponseOuterProp model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */

class Dummy200ResponseOuterProp 
{
        /**
     * @var Dummy200ResponseOuterPropInnerProp|null
     * @SerializedName("innerProp")
     * @Assert\Type("OpenAPI\Server\Model\Dummy200ResponseOuterPropInnerProp")
     * @Type("OpenAPI\Server\Model\Dummy200ResponseOuterPropInnerProp")
     */
    protected ?Dummy200ResponseOuterPropInnerProp $innerProp = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->innerProp = $data['innerProp'] ?? null;
    }

    /**
     * Gets innerProp.
     *
     * @return Dummy200ResponseOuterPropInnerProp|null
     */
    public function getInnerProp(): ?Dummy200ResponseOuterPropInnerProp
    {
        return $this->innerProp;
    }

    /**
     * Sets innerProp.
     *
     * @param Dummy200ResponseOuterPropInnerProp|null $innerProp
     *
     * @return $this
     */
    public function setInnerProp(?Dummy200ResponseOuterPropInnerProp $innerProp = null): self
    {
        $this->innerProp = $innerProp;

        return $this;
    }
}


