<?php
/**
 * Dummy200Response
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * dummy
 *
 * dummy
 *
 * The version of the OpenAPI document: dummy
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Dummy200Response model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */

class Dummy200Response 
{
        /**
     * @var Dummy200ResponseOuterProp|null
     * @SerializedName("outerProp")
     * @Assert\Type("OpenAPI\Server\Model\Dummy200ResponseOuterProp")
     * @Type("OpenAPI\Server\Model\Dummy200ResponseOuterProp")
     */
    protected ?Dummy200ResponseOuterProp $outerProp = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->outerProp = $data['outerProp'] ?? null;
    }

    /**
     * Gets outerProp.
     *
     * @return Dummy200ResponseOuterProp|null
     */
    public function getOuterProp(): ?Dummy200ResponseOuterProp
    {
        return $this->outerProp;
    }

    /**
     * Sets outerProp.
     *
     * @param Dummy200ResponseOuterProp|null $outerProp
     *
     * @return $this
     */
    public function setOuterProp(?Dummy200ResponseOuterProp $outerProp = null): self
    {
        $this->outerProp = $outerProp;

        return $this;
    }
}


