/**
 * dummy
 * dummy
 *
 * OpenAPI spec version: dumy
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace OpenAPI
{

/*
 * OpenAPIExampleResponse
 *
 * dummy
 */
class OPENAPI_API OpenAPIExampleResponse : public Model
{
public:
    virtual ~OpenAPIExampleResponse() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<TSet<double>> MyOnlyProperty;
};

}
