/**
 * dummy
 * dummy
 *
 * OpenAPI spec version: dummy
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIDummy200ResponseOuterPropInnerProp.h"

namespace OpenAPI
{

/*
 * OpenAPIDummy200ResponseOuterProp
 *
 * 
 */
class OPENAPI_API OpenAPIDummy200ResponseOuterProp : public Model
{
public:
    virtual ~OpenAPIDummy200ResponseOuterProp() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<OpenAPIDummy200ResponseOuterPropInnerProp> InnerProp;
};

}
