/**
 * dummy
 * dummy
 *
 * OpenAPI spec version: dummy
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace OpenAPI
{

/*
 * OpenAPINode
 *
 * dummy
 */
class OPENAPI_API OpenAPINode : public Model
{
public:
    virtual ~OpenAPINode() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<OpenAPINode> Left;
	TOptional<OpenAPINode> Right;
};

}
