/**
 * dummy
 * dummy
 *
 * OpenAPI spec version: dummy
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIExampleResponse.h"

namespace OpenAPI
{

/*
 * OpenAPIOtherObject
 *
 * dummy
 */
class OPENAPI_API OpenAPIOtherObject : public Model
{
public:
    virtual ~OpenAPIOtherObject() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<OpenAPIExampleResponse> MyOnlyProperty2;
};

}
