/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.Serializable as KSerializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import java.io.Serializable

/**
 * dummy
 *
 * @param left 
 * @param right 
 */
@KSerializable

data class Node (

    @SerialName(value = "left")
    val left: Node? = null,

    @SerialName(value = "right")
    val right: Node? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

