/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ExampleResponse

import kotlinx.serialization.Serializable as KSerializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import java.io.Serializable

/**
 * dummy
 *
 * @param myOnlyProperty2 
 */
@KSerializable

data class OtherObject (

    @SerialName(value = "myOnlyProperty2")
    val myOnlyProperty2: ExampleResponse? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

