# coding: utf-8

"""
    dummy

    dummy  # noqa: E501

    The version of the OpenAPI document: dummy
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import petstore_api
from petstore_api.models.dummy200_response import Dummy200Response  # noqa: E501
from petstore_api.rest import ApiException

class TestDummy200Response(unittest.TestCase):
    """Dummy200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Dummy200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Dummy200Response`
        """
        model = petstore_api.models.dummy200_response.Dummy200Response()  # noqa: E501
        if include_optional :
            return Dummy200Response(
                outer_prop = petstore_api.models.dummy_200_response_outer_prop.dummy_200_response_outerProp(
                    inner_prop = petstore_api.models.dummy_200_response_outer_prop_inner_prop.dummy_200_response_outerProp_innerProp(
                        my_bool = True, ), )
            )
        else :
            return Dummy200Response(
        )
        """

    def testDummy200Response(self):
        """Test Dummy200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
