# coding: utf-8

"""
    dummy

    dummy  # noqa: E501

    The version of the OpenAPI document: dumy
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import petstore_api
from petstore_api.api.default_api import DefaultApi  # noqa: E501
from petstore_api.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = petstore_api.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_dummy(self):
        """Test case for dummy

        """
        pass


if __name__ == '__main__':
    unittest.main()
