/**
 * dummy
 * dummy
 *
 * The version of the OpenAPI document: dummy
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Dummy);
  }
}(this, function(expect, Dummy) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Dummy.Dummy200Response();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Dummy200Response', function() {
    it('should create an instance of Dummy200Response', function() {
      // uncomment below and update the code to test Dummy200Response
      //var instance = new Dummy.Dummy200Response();
      //expect(instance).to.be.a(Dummy.Dummy200Response);
    });

    it('should have the property outerProp (base name: "outerProp")', function() {
      // uncomment below and update the code to test the property outerProp
      //var instance = new Dummy.Dummy200Response();
      //expect(instance).to.be();
    });

  });

}));
