/*
 * dummy
 * dummy
 *
 * The version of the OpenAPI document: dummy
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.server.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for ExampleResponse
 */
public class ExampleResponseTest {
    private final ExampleResponse model = new ExampleResponse();

    /**
     * Model tests for ExampleResponse
     */
    @Test
    public void testExampleResponse() {
        // TODO: test ExampleResponse
    }

    /**
     * Test the property 'emptyString'
     */
    @Test
    public void emptyStringTest() {
        // TODO: test emptyString
    }

    /**
     * Test the property 'numberString'
     */
    @Test
    public void numberStringTest() {
        // TODO: test numberString
    }

    /**
     * Test the property 'boolString'
     */
    @Test
    public void boolStringTest() {
        // TODO: test boolString
    }

    /**
     * Test the property 'nullString'
     */
    @Test
    public void nullStringTest() {
        // TODO: test nullString
    }

    /**
     * Test the property 'aBool'
     */
    @Test
    public void aBoolTest() {
        // TODO: test aBool
    }

    /**
     * Test the property 'zero'
     */
    @Test
    public void zeroTest() {
        // TODO: test zero
    }

}
