/*
 * dummy
 * dummy
 *
 * The version of the OpenAPI document: dummy
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.server.model;

import org.openapitools.server.model.ExampleResponse;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OtherObject
 */
public class OtherObjectTest {
    private final OtherObject model = new OtherObject();

    /**
     * Model tests for OtherObject
     */
    @Test
    public void testOtherObject() {
        // TODO: test OtherObject
    }

    /**
     * Test the property 'myOnlyProperty2'
     */
    @Test
    public void myOnlyProperty2Test() {
        // TODO: test myOnlyProperty2
    }

}
