//
// Dummy200ResponseOuterPropInnerProp.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "PetstoreClientAPI.Dummy200ResponseOuterPropInnerProp")
public typealias Dummy200ResponseOuterPropInnerProp = PetstoreClientAPI.Dummy200ResponseOuterPropInnerProp

extension PetstoreClientAPI {

public final class Dummy200ResponseOuterPropInnerProp: Codable, JSONEncodable, Hashable {

    public var myBool: Bool?

    public init(myBool: Bool? = nil) {
        self.myBool = myBool
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case myBool
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(myBool, forKey: .myBool)
    }

    public static func == (lhs: Dummy200ResponseOuterPropInnerProp, rhs: Dummy200ResponseOuterPropInnerProp) -> Bool {
        lhs.myBool == rhs.myBool
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(myBool?.hashValue)
        
    }
}

}
