#
# dummy
# dummy
# Version: dummy
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER OuterProp
No description available.
.OUTPUTS

Dummy200Response<PSCustomObject>
#>

function Initialize-PSDummy200Response {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${OuterProp}
    )

    Process {
        'Creating PSCustomObject: PSPetstore => PSDummy200Response' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "outerProp" = ${OuterProp}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to Dummy200Response<PSCustomObject>

.DESCRIPTION

Convert from JSON to Dummy200Response<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

Dummy200Response<PSCustomObject>
#>
function ConvertFrom-PSJsonToDummy200Response {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSPetstore => PSDummy200Response' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in PSDummy200Response
        $AllProperties = ("outerProp")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "outerProp"))) { #optional property not found
            $OuterProp = $null
        } else {
            $OuterProp = $JsonParameters.PSobject.Properties["outerProp"].value
        }

        $PSO = [PSCustomObject]@{
            "outerProp" = ${OuterProp}
        }

        return $PSO
    }

}

