#
# dummy
# dummy
# Version: dummy
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

dummy

.PARAMETER MyOnlyProperty2
No description available.
.OUTPUTS

OtherObject<PSCustomObject>
#>

function Initialize-PSOtherObject {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${MyOnlyProperty2}
    )

    Process {
        'Creating PSCustomObject: PSPetstore => PSOtherObject' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "myOnlyProperty2" = ${MyOnlyProperty2}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to OtherObject<PSCustomObject>

.DESCRIPTION

Convert from JSON to OtherObject<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

OtherObject<PSCustomObject>
#>
function ConvertFrom-PSJsonToOtherObject {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSPetstore => PSOtherObject' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in PSOtherObject
        $AllProperties = ("myOnlyProperty2")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "myOnlyProperty2"))) { #optional property not found
            $MyOnlyProperty2 = $null
        } else {
            $MyOnlyProperty2 = $JsonParameters.PSobject.Properties["myOnlyProperty2"].value
        }

        $PSO = [PSCustomObject]@{
            "myOnlyProperty2" = ${MyOnlyProperty2}
        }

        return $PSO
    }

}

