<?php

/**
 * Some example
 * dummy description
 * PHP version 7.2.5
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;

class DefaultApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation retrieveSomething
     *
     * .
     *
     *
     * @return Http response
     */
    public function retrieveSomething()
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing retrieveSomething as a get method ?');
    }
}
