openapi: 3.0.0
info:
  description: dummy
  title: dummy
  version: dummy
  x-myextension: dummy
servers:
- url: /
paths:
  /example/someMethod:
    get:
      description: dummy
      operationId: dummy
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/dummy_200_response'
              x-myextension: dummy
          description: dummy
          x-myextension: dummy
        x-myextension: dummy
      x-myextension: dummy
      x-accepts: '*/*'
    x-myextension: dummy
components:
  schemas:
    ExampleResponse:
      description: dummy
      properties:
        myOnlyProperty:
          $ref: '#/components/schemas/OtherObject'
      type: object
      x-myextension: dummy
    OtherObject:
      description: dummy
      properties:
        myOnlyProperty2:
          $ref: '#/components/schemas/ExampleResponse'
      type: object
    Node:
      description: dummy
      properties:
        left:
          $ref: '#/components/schemas/Node'
        right:
          $ref: '#/components/schemas/Node'
      type: object
    dummy_200_response_outerProp_innerProp:
      example:
        myBool: true
      properties:
        myBool:
          type: boolean
      type: object
    dummy_200_response_outerProp:
      example:
        innerProp:
          myBool: true
      properties:
        innerProp:
          $ref: '#/components/schemas/dummy_200_response_outerProp_innerProp'
      type: object
      x-myextension: dummy
    dummy_200_response:
      example:
        outerProp:
          innerProp:
            myBool: true
      properties:
        outerProp:
          $ref: '#/components/schemas/dummy_200_response_outerProp'
      type: object
      x-myextension: dummy
  x-myextension: dummy
x-myextension: dummy
