/**
 * dummy
 * dummy
 *
 * The version of the OpenAPI document: dummy
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Dummy200ResponseOuterPropInnerProp model module.
 * @module model/Dummy200ResponseOuterPropInnerProp
 * @version dummy
 */
class Dummy200ResponseOuterPropInnerProp {
    /**
     * Constructs a new <code>Dummy200ResponseOuterPropInnerProp</code>.
     * @alias module:model/Dummy200ResponseOuterPropInnerProp
     */
    constructor() { 
        
        Dummy200ResponseOuterPropInnerProp.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Dummy200ResponseOuterPropInnerProp</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Dummy200ResponseOuterPropInnerProp} obj Optional instance to populate.
     * @return {module:model/Dummy200ResponseOuterPropInnerProp} The populated <code>Dummy200ResponseOuterPropInnerProp</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Dummy200ResponseOuterPropInnerProp();

            if (data.hasOwnProperty('myBool')) {
                obj['myBool'] = ApiClient.convertToType(data['myBool'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Dummy200ResponseOuterPropInnerProp</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Dummy200ResponseOuterPropInnerProp</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Boolean} myBool
 */
Dummy200ResponseOuterPropInnerProp.prototype['myBool'] = undefined;






export default Dummy200ResponseOuterPropInnerProp;

