/* tslint:disable */
/* eslint-disable */
/**
 * dummy
 * dummy
 *
 * The version of the OpenAPI document: dumy
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * dummy
 * @export
 * @interface ExampleResponse
 */
export interface ExampleResponse {
    /**
     * 
     * @type {Set<number>}
     * @memberof ExampleResponse
     */
    'myOnlyProperty'?: Set<number>;
}

