# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DefaultApi")

api_instance <- DefaultApi$new()

test_that("Dummy", {
  # tests for Dummy
  # base path: http://localhost
  # dummy
  # @return [ExampleResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
