# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DefaultApi")

api_instance <- DefaultApi$new()

test_that("ExampleSomeMethodGet", {
  # tests for ExampleSomeMethodGet
  # base path: http://localhost
  # 
  # @return [ExampleResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
