/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Dummy200ResponseOuterPropInnerProp

import com.google.gson.annotations.SerializedName
import org.openapitools.client.models.room.Dummy200ResponseOuterPropRoomModel
import org.openapitools.client.infrastructure.ITransformForStorage

/**
 * 
 *
 * @param innerProp 
 */


data class Dummy200ResponseOuterProp (

    @SerializedName("innerProp")
    val innerProp: Dummy200ResponseOuterPropInnerProp? = null

): ITransformForStorage<Dummy200ResponseOuterPropRoomModel> {
    companion object { }
    override fun toRoomModel(): Dummy200ResponseOuterPropRoomModel =
        Dummy200ResponseOuterPropRoomModel(roomTableId = 0,
        innerProp = this.innerProp,
        )

}

