/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Dummy200ResponseOuterProp

import com.google.gson.annotations.SerializedName
import org.openapitools.client.models.room.Dummy200ResponseRoomModel
import org.openapitools.client.infrastructure.ITransformForStorage

/**
 * 
 *
 * @param outerProp 
 */


data class Dummy200Response (

    @SerializedName("outerProp")
    val outerProp: Dummy200ResponseOuterProp? = null

): ITransformForStorage<Dummy200ResponseRoomModel> {
    companion object { }
    override fun toRoomModel(): Dummy200ResponseRoomModel =
        Dummy200ResponseRoomModel(roomTableId = 0,
        outerProp = this.outerProp,
        )

}

