/* tslint:disable */
/* eslint-disable */
/**
 * 
 * dummy description
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {ApiRecordUtils, knownRecordFactories} from "../runtimeSagasAndRecords";
import {getApiEntitiesState} from "../ApiEntitiesSelectors"
import {List, Record, RecordOf, Map} from 'immutable';
import {Schema, schema, NormalizedSchema} from "normalizr";
import {select, call} from "redux-saga/effects";

import {
    ExampleResponse,
} from './ExampleResponse';



export const ExampleResponseRecordProps = {
    recType: "ExampleResponseApiRecord" as "ExampleResponseApiRecord",
    myOnlyProperty: null as List<boolean> | null,
};

export type ExampleResponseRecordPropsType = typeof ExampleResponseRecordProps;
export const ExampleResponseRecord = Record(ExampleResponseRecordProps, ExampleResponseRecordProps.recType);
export type ExampleResponseRecord = RecordOf<ExampleResponseRecordPropsType>;

knownRecordFactories.set(ExampleResponseRecordProps.recType, ExampleResponseRecord);


class ExampleResponseRecordUtils extends ApiRecordUtils<ExampleResponse, ExampleResponseRecord> {
    public normalize(apiObject: ExampleResponse, asEntity?: boolean): ExampleResponse {
        (apiObject as any).recType = ExampleResponseRecordProps.recType;
        return apiObject;
    }

    public toApi(record: ExampleResponseRecord): ExampleResponse {
        const apiObject = super.toApi(record);
        return apiObject;
    }
}

export const exampleResponseRecordUtils = new ExampleResponseRecordUtils();


