/* tslint:disable */
/* eslint-disable */
/**
 * dummy
 * dummy
 *
 * The version of the OpenAPI document: dummy
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ExampleResponse } from './ExampleResponse';
import {
    ExampleResponseFromJSON,
    ExampleResponseFromJSONTyped,
    ExampleResponseToJSON,
} from './ExampleResponse';

/**
 * dummy
 * @export
 * @interface OtherObject
 */
export interface OtherObject {
    /**
     * 
     * @type {ExampleResponse}
     * @memberof OtherObject
     */
    myOnlyProperty2?: ExampleResponse;
}

/**
 * Check if a given object implements the OtherObject interface.
 */
export function instanceOfOtherObject(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OtherObjectFromJSON(json: any): OtherObject {
    return OtherObjectFromJSONTyped(json, false);
}

export function OtherObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): OtherObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'myOnlyProperty2': !exists(json, 'myOnlyProperty2') ? undefined : ExampleResponseFromJSON(json['myOnlyProperty2']),
    };
}

export function OtherObjectToJSON(value?: OtherObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'myOnlyProperty2': ExampleResponseToJSON(value.myOnlyProperty2),
    };
}

