# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""
    Dummy200Response(;
        outerProp=nothing,
    )

    - outerProp::Dummy200ResponseOuterProp
"""
Base.@kwdef mutable struct Dummy200Response <: OpenAPI.APIModel
    outerProp = nothing # spec type: Union{ Nothing, Dummy200ResponseOuterProp }

    function Dummy200Response(outerProp, )
        OpenAPI.validate_property(Dummy200Response, Symbol("outerProp"), outerProp)
        return new(outerProp, )
    end
end # type Dummy200Response

const _property_types_Dummy200Response = Dict{Symbol,String}(Symbol("outerProp")=>"Dummy200ResponseOuterProp", )
OpenAPI.property_type(::Type{ Dummy200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Dummy200Response[name]))}

function check_required(o::Dummy200Response)
    true
end

function OpenAPI.validate_property(::Type{ Dummy200Response }, name::Symbol, val)
end
