openapi: 3.0.0
info:
  description: dummy
  title: dummy
  version: dummy
servers:
- url: /
paths:
  /example/someMethod:
    get:
      description: dummy
      operationId: dummy
      responses:
        "201":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ExampleResponse'
          description: dummy
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/dummy_200_response'
              x-myextension: dummy
          description: dummy
          x-myextension: dummy
components:
  schemas:
    OtherObject:
      description: dummy
      properties:
        myOnlyProperty2:
          $ref: '#/components/schemas/ExampleResponse'
      type: object
    Node:
      description: dummy
      properties:
        left:
          $ref: '#/components/schemas/Node'
        right:
          $ref: '#/components/schemas/Node'
      title: Node
      type: object
    ExampleResponse:
      description: dummy
      properties:
        emptyString:
          default: ""
          example: ""
          title: emptyString
          type: string
        numberString:
          default: "42"
          example: "42"
          title: numberString
          type: string
        boolString:
          default: "false"
          example: "false"
          title: boolString
          type: string
        nullString:
          default: "null"
          example: "null"
          title: nullString
          type: string
        aBool:
          default: false
          example: false
          title: aBool
          type: boolean
        zero:
          default: 0
          example: 0
          title: zero
          type: integer
      title: ExampleResponse
      type: object
    dummy_200_response_outerProp_innerProp:
      example:
        myBool: true
      properties:
        myBool:
          title: myBool
          type: boolean
      title: dummy_200_response_outerProp_innerProp
      type: object
    dummy_200_response_outerProp:
      example:
        innerProp:
          myBool: true
      properties:
        innerProp:
          $ref: '#/components/schemas/dummy_200_response_outerProp_innerProp'
      title: dummy_200_response_outerProp
      type: object
      x-myextension: dummy
    dummy_200_response:
      example:
        outerProp:
          innerProp:
            myBool: true
      properties:
        outerProp:
          $ref: '#/components/schemas/dummy_200_response_outerProp'
      title: dummy_200_response
      type: object
      x-myextension: dummy
