// <auto-generated>
/*
 * dummy
 *
 * dummy
 *
 * The version of the OpenAPI document: dummy
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenAPIClientUtils = Org.OpenAPITools.Client.ClientUtils;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Dummy200ResponseOuterProp
    /// </summary>
    public partial class Dummy200ResponseOuterProp : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Dummy200ResponseOuterProp" /> class.
        /// </summary>
        /// <param name="innerProp">innerProp</param>
        [JsonConstructor]
        public Dummy200ResponseOuterProp(Dummy200ResponseOuterPropInnerProp innerProp)
        {
            InnerProp = innerProp;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets InnerProp
        /// </summary>
        [JsonPropertyName("innerProp")]
        public Dummy200ResponseOuterPropInnerProp InnerProp { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Dummy200ResponseOuterProp {\n");
            sb.Append("  InnerProp: ").Append(InnerProp).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Dummy200ResponseOuterProp" />
    /// </summary>
    public class Dummy200ResponseOuterPropJsonConverter : JsonConverter<Dummy200ResponseOuterProp>
    {
        /// <summary>
        /// Deserializes json to <see cref="Dummy200ResponseOuterProp" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Dummy200ResponseOuterProp Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Dummy200ResponseOuterPropInnerProp? innerProp = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? propertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (propertyName)
                    {
                        case "innerProp":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                innerProp = JsonSerializer.Deserialize<Dummy200ResponseOuterPropInnerProp>(ref utf8JsonReader, jsonSerializerOptions);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (innerProp == null)
                throw new ArgumentNullException(nameof(innerProp), "Property is required for class Dummy200ResponseOuterProp.");

            return new Dummy200ResponseOuterProp(innerProp);
        }

        /// <summary>
        /// Serializes a <see cref="Dummy200ResponseOuterProp" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="dummy200ResponseOuterProp"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Dummy200ResponseOuterProp dummy200ResponseOuterProp, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            writer.WritePropertyName("innerProp");
            JsonSerializer.Serialize(writer, dummy200ResponseOuterProp.InnerProp, jsonSerializerOptions);

            writer.WriteEndObject();
        }
    }
}
