openapi: 3.0.0
info:
  description: dummy description
  title: ""
  version: ""
servers:
- url: /
paths:
  /example/someMethod:
    get:
      description: get some object
      operationId: retrieveSomething
      responses:
        "200":
          content:
            /:
              schema:
                $ref: '#/components/schemas/ExampleResponse'
          description: The response with results
components:
  schemas:
    ExampleResponse:
      properties:
        myOnlyProperty:
          items:
            type: boolean
          type: array
      type: object
