/*
 * dummy
 * dummy
 *
 * The version of the OpenAPI document: dummy
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.dataformat.xml.annotation.*;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.*;
import io.github.threetenjaxb.core.*;

/**
 * dummy
 */
@JsonPropertyOrder({
  ExampleResponse.JSON_PROPERTY_EMPTY_STRING,
  ExampleResponse.JSON_PROPERTY_NUMBER_STRING,
  ExampleResponse.JSON_PROPERTY_BOOL_STRING,
  ExampleResponse.JSON_PROPERTY_NULL_STRING,
  ExampleResponse.JSON_PROPERTY_A_BOOL,
  ExampleResponse.JSON_PROPERTY_ZERO
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
@XmlRootElement(name = "ExampleResponse")
@XmlAccessorType(XmlAccessType.FIELD)
@JacksonXmlRootElement(localName = "ExampleResponse")
public class ExampleResponse {
  public static final String JSON_PROPERTY_EMPTY_STRING = "emptyString";
  @XmlElement(name = "emptyString")
  private String emptyString = "";

  public static final String JSON_PROPERTY_NUMBER_STRING = "numberString";
  @XmlElement(name = "numberString")
  private String numberString = "42";

  public static final String JSON_PROPERTY_BOOL_STRING = "boolString";
  @XmlElement(name = "boolString")
  private String boolString = "false";

  public static final String JSON_PROPERTY_NULL_STRING = "nullString";
  @XmlElement(name = "nullString")
  private String nullString = "null";

  public static final String JSON_PROPERTY_A_BOOL = "aBool";
  @XmlElement(name = "aBool")
  private Boolean aBool = false;

  public static final String JSON_PROPERTY_ZERO = "zero";
  @XmlElement(name = "zero")
  private Integer zero = 0;

  public ExampleResponse() {
  }

  public ExampleResponse emptyString(String emptyString) {
    
    this.emptyString = emptyString;
    return this;
  }

   /**
   * Get emptyString
   * @return emptyString
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EMPTY_STRING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "emptyString")

  public String getEmptyString() {
    return emptyString;
  }


  @JsonProperty(JSON_PROPERTY_EMPTY_STRING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "emptyString")
  public void setEmptyString(String emptyString) {
    this.emptyString = emptyString;
  }


  public ExampleResponse numberString(String numberString) {
    
    this.numberString = numberString;
    return this;
  }

   /**
   * Get numberString
   * @return numberString
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NUMBER_STRING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "numberString")

  public String getNumberString() {
    return numberString;
  }


  @JsonProperty(JSON_PROPERTY_NUMBER_STRING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "numberString")
  public void setNumberString(String numberString) {
    this.numberString = numberString;
  }


  public ExampleResponse boolString(String boolString) {
    
    this.boolString = boolString;
    return this;
  }

   /**
   * Get boolString
   * @return boolString
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BOOL_STRING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "boolString")

  public String getBoolString() {
    return boolString;
  }


  @JsonProperty(JSON_PROPERTY_BOOL_STRING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "boolString")
  public void setBoolString(String boolString) {
    this.boolString = boolString;
  }


  public ExampleResponse nullString(String nullString) {
    
    this.nullString = nullString;
    return this;
  }

   /**
   * Get nullString
   * @return nullString
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NULL_STRING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "nullString")

  public String getNullString() {
    return nullString;
  }


  @JsonProperty(JSON_PROPERTY_NULL_STRING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "nullString")
  public void setNullString(String nullString) {
    this.nullString = nullString;
  }


  public ExampleResponse aBool(Boolean aBool) {
    
    this.aBool = aBool;
    return this;
  }

   /**
   * Get aBool
   * @return aBool
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_A_BOOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "aBool")

  public Boolean getaBool() {
    return aBool;
  }


  @JsonProperty(JSON_PROPERTY_A_BOOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "aBool")
  public void setaBool(Boolean aBool) {
    this.aBool = aBool;
  }


  public ExampleResponse zero(Integer zero) {
    
    this.zero = zero;
    return this;
  }

   /**
   * Get zero
   * @return zero
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ZERO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "zero")

  public Integer getZero() {
    return zero;
  }


  @JsonProperty(JSON_PROPERTY_ZERO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "zero")
  public void setZero(Integer zero) {
    this.zero = zero;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExampleResponse exampleResponse = (ExampleResponse) o;
    return Objects.equals(this.emptyString, exampleResponse.emptyString) &&
        Objects.equals(this.numberString, exampleResponse.numberString) &&
        Objects.equals(this.boolString, exampleResponse.boolString) &&
        Objects.equals(this.nullString, exampleResponse.nullString) &&
        Objects.equals(this.aBool, exampleResponse.aBool) &&
        Objects.equals(this.zero, exampleResponse.zero);
  }

  @Override
  public int hashCode() {
    return Objects.hash(emptyString, numberString, boolString, nullString, aBool, zero);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExampleResponse {\n");
    sb.append("    emptyString: ").append(toIndentedString(emptyString)).append("\n");
    sb.append("    numberString: ").append(toIndentedString(numberString)).append("\n");
    sb.append("    boolString: ").append(toIndentedString(boolString)).append("\n");
    sb.append("    nullString: ").append(toIndentedString(nullString)).append("\n");
    sb.append("    aBool: ").append(toIndentedString(aBool)).append("\n");
    sb.append("    zero: ").append(toIndentedString(zero)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

