#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* dummy
* dummy
*
* The version of the OpenAPI document: dummy
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol SWGDummy200ResponseOuterPropInnerProp
@end

@interface SWGDummy200ResponseOuterPropInnerProp : SWGObject


@property(nonatomic) NSNumber* myBool;

@end
