#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* 
* dummy description
*
* The version of the OpenAPI document: 
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol SWGExampleResponse
@end

@interface SWGExampleResponse : SWGObject


@property(nonatomic) NSArray<NSNumber*>* myOnlyProperty;

@end
