#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* dummy
* dummy
*
* The version of the OpenAPI document: dummy
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "SWGExampleResponse.h"
@protocol SWGExampleResponse;
@class SWGExampleResponse;



@protocol SWGOtherObject
@end

@interface SWGOtherObject : SWGObject


@property(nonatomic) SWGExampleResponse* myOnlyProperty2;

@end
