openapi: 3.0.0
info:
  description: "This spec is mainly for testing Petstore server and contains fake\
    \ endpoints, models. Please do not use this for any other purpose. Special characters:\
    \ \" \\"
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: OpenAPI Petstore
  version: 1.0.0
servers:
- url: /
paths:
  /foo:
    get:
      responses:
        default:
          content:
            application/json:
              schema:
                properties:
                  myString:
                    $ref: '#/components/schemas/Foo'
                type: object
          description: response
      x-accepts: application/json
components:
  schemas:
    Foo:
      properties:
        bar:
          default: bar
          type: string
      type: object
    Bar:
      default: bar
      type: string

