/**
* dummy
* dummy
*
* The version of the OpenAPI document: dummy
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Dummy_200_response_outerProp_innerProp.h
 *
 * 
 */

#ifndef Dummy_200_response_outerProp_innerProp_H_
#define Dummy_200_response_outerProp_innerProp_H_


#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// 
/// </summary>
class  Dummy_200_response_outerProp_innerProp
{
public:
    Dummy_200_response_outerProp_innerProp();
    virtual ~Dummy_200_response_outerProp_innerProp() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const Dummy_200_response_outerProp_innerProp& rhs) const;
    bool operator!=(const Dummy_200_response_outerProp_innerProp& rhs) const;

    /////////////////////////////////////////////
    /// Dummy_200_response_outerProp_innerProp members

    /// <summary>
    /// 
    /// </summary>
    bool isMyBool() const;
    void setMyBool(bool const value);
    bool myBoolIsSet() const;
    void unsetMyBool();

    friend  void to_json(nlohmann::json& j, const Dummy_200_response_outerProp_innerProp& o);
    friend  void from_json(const nlohmann::json& j, Dummy_200_response_outerProp_innerProp& o);
protected:
    bool m_MyBool;
    bool m_MyBoolIsSet;
    
};

} // namespace org::openapitools::server::model

#endif /* Dummy_200_response_outerProp_innerProp_H_ */
