openapi: 3.0.0
info:
  description: dummy description
  title: ""
  version: ""
servers:
- url: /
paths:
  /example/someMethod:
    get:
      description: get some object
      operationId: retrieve_something
      responses:
        "200":
          content:
            /:
              schema:
                $ref: '#/components/schemas/ExampleResponse'
          description: The response with results
      x-openapi-router-controller: openapi_server.controllers.default_controller
components:
  schemas:
    ExampleResponse:
      properties:
        myOnlyProperty:
          items:
            type: boolean
          title: myOnlyProperty
          type: array
      title: ExampleResponse
      type: object
