openapi: 3.0.0
info:
  description: dummy
  title: dummy
  version: dummy
servers:
- url: /
paths:
  /example/someMethod:
    get:
      description: dummy
      operationId: dummy
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ExampleResponse'
          description: dummy
      x-openapi-router-controller: openapi_server.controllers.default_controller
components:
  schemas:
    ExampleResponse:
      description: dummy
      example:
        zero: 0
        numberString: "42"
        nullString: "null"
        emptyString: ""
        boolString: "false"
        aBool: false
      properties:
        emptyString:
          default: ""
          example: ""
          title: emptyString
          type: string
        numberString:
          default: "42"
          example: "42"
          title: numberString
          type: string
        boolString:
          default: "false"
          example: "false"
          title: boolString
          type: string
        nullString:
          default: "null"
          example: "null"
          title: nullString
          type: string
        aBool:
          default: false
          example: false
          title: aBool
          type: boolean
        zero:
          default: 0
          example: 0
          title: zero
          type: integer
      title: ExampleResponse
      type: object
