/*
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ExampleResponse 
    {
        /// <summary>
        /// Gets or Sets MyOnlyProperty
        /// </summary>
        [DataMember(Name="myOnlyProperty", EmitDefaultValue=false)]
        public List<bool> MyOnlyProperty { get; set; }

    }
}
