# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DefaultApi")

api_instance <- DefaultApi$new()

test_that("retrieve_something", {
  # tests for retrieve_something
  # base path: http://localhost
  # get some object
  # @return [array[numeric]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
