/**
 * Some example
 * dummy description
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.api;

import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;
import java.util.Set;

import jakarta.ws.rs.*;
import jakarta.ws.rs.core.Response;
import jakarta.ws.rs.core.MediaType;

import org.eclipse.microprofile.rest.client.annotation.RegisterProvider;
import org.eclipse.microprofile.rest.client.inject.RegisterRestClient;

import org.openapitools.client.model.ExampleResponse;

/**
 * Some example
 *
 * <p>dummy description
 */
@RegisterRestClient
@RegisterProvider(ApiExceptionMapper.class)
@Path("/example/someMethod")
public interface DefaultApi  {

    @GET
    
    @Produces({ "application/json" })
    ExampleResponse retrieveSomething() throws ApiException, ProcessingException;
}
