#import <Foundation/Foundation.h>
#import <AFNetworking/AFURLRequestSerialization.h>

/**
* 
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


@interface SWGJSONRequestSerializer : AFJSONRequestSerializer
@end
