/* tslint:disable */
/* eslint-disable */
/**
 * dummy
 * dummy
 *
 * The version of the OpenAPI document: dummy
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OtherObject } from './OtherObject';
import {
    OtherObjectFromJSON,
    OtherObjectFromJSONTyped,
    OtherObjectToJSON,
} from './OtherObject';

/**
 * dummy
 * @export
 * @interface ExampleResponse
 */
export interface ExampleResponse {
    /**
     * 
     * @type {OtherObject}
     * @memberof ExampleResponse
     */
    myOnlyProperty?: OtherObject;
}

/**
 * Check if a given object implements the ExampleResponse interface.
 */
export function instanceOfExampleResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ExampleResponseFromJSON(json: any): ExampleResponse {
    return ExampleResponseFromJSONTyped(json, false);
}

export function ExampleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExampleResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'myOnlyProperty': !exists(json, 'myOnlyProperty') ? undefined : OtherObjectFromJSON(json['myOnlyProperty']),
    };
}

export function ExampleResponseToJSON(value?: ExampleResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'myOnlyProperty': OtherObjectToJSON(value.myOnlyProperty),
    };
}

