# NOTE: This file is auto generated by OpenAPI Generator 7.0.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenapiPetstore.Api.Default do
  @moduledoc """
  API calls for all endpoints tagged `Default`.
  """

  alias OpenapiPetstore.Connection
  import OpenapiPetstore.RequestBuilder

  @doc """
  get some object

  ### Parameters

  - `connection` (OpenapiPetstore.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, OpenapiPetstore.Model.ExampleResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec retrieve_something(Tesla.Env.client, keyword()) :: {:ok, OpenapiPetstore.Model.ExampleResponse.t} | {:error, Tesla.Env.t}
  def retrieve_something(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/example/someMethod")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %OpenapiPetstore.Model.ExampleResponse{}}
    ])
  end
end
