#
# 
# 
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# The version of the OpenAPI document: 
# 
# Generated by: https://openapi-generator.tech
#

import json
import tables


type ExampleResponse* = object
  ## 
  myOnlyProperty*: seq[bool]
