# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Dummy200ResponseOuterProp")

model_instance <- Dummy200ResponseOuterProp$new()

test_that("innerProp", {
  # tests for the property `innerProp` (Dummy200ResponseOuterPropInnerProp)

  # uncomment below to test the property
  #expect_equal(model.instance$`innerProp`, "EXPECTED_RESULT")
})
