# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ExampleResponse")

model_instance <- ExampleResponse$new()

test_that("myOnlyProperty", {
  # tests for the property `myOnlyProperty` (OtherObject)

  # uncomment below to test the property
  #expect_equal(model.instance$`myOnlyProperty`, "EXPECTED_RESULT")
})
