#import <Foundation/Foundation.h>
#import "SWGApi.h"

/**
* Some example
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface SWGDefaultApi: NSObject <SWGApi>

extern NSString* kSWGDefaultApiErrorDomain;
extern NSInteger kSWGDefaultApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// get some object
///
/// 
///  code:200 message:"The response with results"
///
/// @return NSArray<NSNumber*>*
-(NSURLSessionTask*) retrieveSomethingWithCompletionHandler: 
    (void (^)(NSArray<NSNumber*>* output, NSError* error)) handler;



@end
