#import <Foundation/Foundation.h>
#import "SWGExampleResponse.h"
#import "SWGApi.h"

/**
* dummy
* dummy
*
* The version of the OpenAPI document: dummy
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface SWGDefaultApi: NSObject <SWGApi>

extern NSString* kSWGDefaultApiErrorDomain;
extern NSInteger kSWGDefaultApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// dummy
///
/// 
///  code:200 message:"dummy"
///
/// @return SWGExampleResponse*
-(NSURLSessionTask*) dummyWithCompletionHandler: 
    (void (^)(SWGExampleResponse* output, NSError* error)) handler;



@end
