generatorName: cpp-ue4
outputDir: samples/client/petstore/cpp-ue4
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/cpp-ue4
