generatorName: cpp-pistache-server
outputDir: samples/server/petstore/cpp-pistache
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/cpp-pistache-server
additionalProperties:
  useStructModel: "false"
  addExternalLibs: "true"
