# for .net standard
generatorName: csharp-netcore
outputDir: samples/client/petstore/csharp-netcore/OpenAPIClient-ConditionalSerialization
inputSpec: modules/openapi-generator/src/test/resources/experiments.yaml
templateDir: modules/openapi-generator/src/main/resources/csharp-netcore
additionalProperties:
  packageGuid: '{fa96c953-af24-457d-8a01-f2fd2a7547a9}'
  useCompareNetObjects: true 
  disallowAdditionalPropertiesIfNotPresent: false
  useOneOfDiscriminatorLookup: true
  targetFramework:  netstandard2.0
  conditionalSerialization: true
