generatorName: dart
outputDir: samples/openapi3/client/petstore/dart2/petstore_client_lib_fake
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/dart2
typeMappings:
  Client: "ModelClient"
  File: "ModelFile"
additionalProperties:
  hideGenerationTimestamp: "true"
