generatorName: erlang-server
outputDir: samples/server/petstore/erlang-server
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/erlang-server
