generatorName: erlang-proper
outputDir: samples/client/petstore/erlang-proper
inputSpec: modules/openapi-generator/src/test/resources/experiments.yaml
templateDir: modules/openapi-generator/src/main/resources/erlang-proper
additionalProperties:
  packageName: petstore
