generatorName: go-server
outputDir: samples/server/petstore/go-api-server
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/go-server
additionalProperties:
  hideGenerationTimestamp: "true"
  packageName: petstoreserver
  addResponseHeaders: true
