generatorName: go-server
outputDir: samples/server/petstore/go-server-required
inputSpec: modules/openapi-generator/src/test/resources/experiments.yaml
templateDir: modules/openapi-generator/src/main/resources/go-server
additionalProperties:
  hideGenerationTimestamp: "true"
  packageName: petstoreserver
  addResponseHeaders: true
  router: "chi"
