generatorName: groovy
outputDir: samples/client/petstore/groovy
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/Groovy
additionalProperties:
  hideGenerationTimestamp: "true"
