generatorName: java
outputDir: samples/client/petstore/java/microprofile-rest-client
library: microprofile
inputSpec: modules/openapi-generator/src/test/resources/experiments.yaml
templateDir: modules/openapi-generator/src/main/resources/Java
additionalProperties:
  artifactId: microprofile-rest-client
  configKey: petstore
