generatorName: java-helidon-server
library: se
outputDir: samples/server/petstore/java-helidon-server/se
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/java-helidon/server
additionalProperties:
  artifactId: petstore-helidon-server-se
  hideGenerationTimestamp: "true"
  fullProject: "true"