generatorName: java
outputDir: samples/client/petstore/java/jersey3
library: jersey3
inputSpec: modules/openapi-generator/src/test/resources/experiments.yaml
templateDir: modules/openapi-generator/src/main/resources/Java
additionalProperties:
  artifactId: petstore-jersey3
  hideGenerationTimestamp: true
  serverPort: "8082"
  dateLibrary: java8
  useOneOfDiscriminatorLookup: true
  disallowAdditionalPropertiesIfNotPresent: false
  gradleProperties: "\n# JVM arguments\norg.gradle.jvmargs=-Xmx2024m -XX:MaxPermSize=512m\n# set timeout\norg.gradle.daemon.idletimeout=3600000\n# show all warnings\norg.gradle.warning.mode=all"
