generatorName: java-helidon-server
library: mp
outputDir: samples/server/petstore/java-helidon-server/mp
inputSpec: modules/openapi-generator/src/test/resources/experiments.yaml
templateDir: modules/openapi-generator/src/main/resources/java-helidon/server
additionalProperties:
  artifactId: petstore-helidon-server-mp
  hideGenerationTimestamp: "true"
  build: "all"
  test: "spock"
  useAuth: "false"
  fullProject: "true"