generatorName: java
outputDir: samples/client/petstore/java/retrofit2rx3
library: retrofit2
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/Java
additionalProperties:
  useRxJava3: "true"
  artifactId: petstore-retrofit2-rx3
  hideGenerationTimestamp: "true"
