generatorName: java
outputDir: samples/client/echo_api/java/okhttp-gson
#library: okhttp-gson
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/Java
additionalProperties:
  artifactId: echo-api-okhttp-gson
  hideGenerationTimestamp: "true"
