generatorName: java
outputDir: samples/client/petstore/java/okhttp-gson
library: okhttp-gson
inputSpec: modules/openapi-generator/src/test/resources/experiments.yaml
templateDir: modules/openapi-generator/src/main/resources/Java
additionalProperties:
  artifactId: petstore-okhttp-gson
  hideGenerationTimestamp: "true"
  useOneOfDiscriminatorLookup: "true"
  disallowAdditionalPropertiesIfNotPresent: false
