generatorName: java-play-framework
outputDir: samples/server/petstore/java-play-framework-no-bean-validation
inputSpec: modules/openapi-generator/src/test/resources/experiments.yaml
templateDir: modules/openapi-generator/src/main/resources/JavaPlayFramework
additionalProperties:
  hideGenerationTimestamp: "true"
  useBeanValidation: "false"
