generatorName: java
outputDir: samples/client/petstore/java/feign-no-nullable
library: feign
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/Java
additionalProperties:
  booleanGetterPrefix: is
  artifactId: petstore-feign-no-nullable
  hideGenerationTimestamp: "true"
  additionalModelTypeAnnotations: '@javax.annotation.concurrent.Immutable'
  openApiNullable: "false"
