generatorName: java
outputDir: samples/client/petstore/java/okhttp-gson-parcelableModel
library: okhttp-gson
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/Java
additionalProperties:
  parcelableModel: "true"
  artifactId: petstore-okhttp-gson-parcelableModel
  hideGenerationTimestamp: "true"
