generatorName: java
outputDir: samples/client/petstore/java/resttemplate-swagger1
library: resttemplate
inputSpec: modules/openapi-generator/src/test/resources/experiments.yaml
templateDir: modules/openapi-generator/src/main/resources/Java
additionalProperties:
  artifactId: petstore-resttemplate
  hideGenerationTimestamp: "true"
  annotationLibrary: "swagger1"
  java8: true
