generatorName: java-play-framework
outputDir: samples/server/petstore/java-play-framework-api-package-override
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/JavaPlayFramework
additionalProperties:
  hideGenerationTimestamp: "true"
  apiPackage: com.puppies.store.apis
