generatorName: java
outputDir: samples/client/petstore/java/webclient
library: webclient
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/Java
additionalProperties:
  artifactId: petstore-webclient
  hideGenerationTimestamp: "true"
  containerDefaultToNull: "true"
