generatorName: java
outputDir: samples/client/petstore/java/resttemplate-withXml
library: resttemplate
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/Java
additionalProperties:
  java8: true
  withXml: "true"
  artifactId: petstore-resttemplate-withxml
  hideGenerationTimestamp: "true"
