generatorName: java
outputDir: samples/client/petstore/java/retrofit2
library: retrofit2
inputSpec: modules/openapi-generator/src/test/resources/experiments.yaml
templateDir: modules/openapi-generator/src/main/resources/Java
additionalProperties:
  artifactId: petstore-retrofit2
  hideGenerationTimestamp: "true"
