generatorName: java-msf4j
outputDir: samples/server/petstore/java-msf4j
inputSpec: modules/openapi-generator/src/test/resources/experiments.yaml
templateDir: modules/openapi-generator/src/main/resources/java-msf4j-server
additionalProperties:
  hideGenerationTimestamp: "true"
  artifactId: java-msf4j-server
