generatorName: java
outputDir: samples/client/petstore/java/feign
library: feign
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/Java
additionalProperties:
  booleanGetterPrefix: is
  artifactId: petstore-feign
  hideGenerationTimestamp: "true"
