generatorName: java
outputDir: samples/client/petstore/java/google-api-client
library: google-api-client
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/Java
additionalProperties:
  artifactId: petstore-google-api-client
  hideGenerationTimestamp: "true"
