generatorName: java-micronaut-server
outputDir: samples/server/petstore/java-micronaut-server/
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
additionalProperties:
  artifactId: petstore-micronaut-server
  hideGenerationTimestamp: "true"
  build: "all"
  test: "spock"
  requiredPropertiesInConstructor: "true"
  useAuth: "false"
  generateControllerAsAbstract: "false"
  generateOperationsToReturnNotImplemented: "true"
