generatorName: java
outputDir: samples/client/petstore/java/vertx
library: vertx
inputSpec: modules/openapi-generator/src/test/resources/experiments.yaml
templateDir: modules/openapi-generator/src/main/resources/Java
additionalProperties:
  artifactId: petstore-vertx
  hideGenerationTimestamp: "true"
  dateLibrary: java8
