generatorName: java-helidon-client
library: mp
outputDir: samples/client/petstore/java-helidon-client/mp
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
additionalProperties:
  artifactId: petstore-helidon-client-mp
  hideGenerationTimestamp: "true"
  configureAuth: "false"
  build: "all"
  test: "spock"
  requiredPropertiesInConstructor: "false"
  visitable: "true"
  fullProject: "true"
