generatorName: java
outputDir: samples/client/petstore/java/microprofile-rest-client-3.0
library: microprofile
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/Java
additionalProperties:
  artifactId: microprofile-rest-client-3
  configKey: petstore
  microprofileRestClientVersion: "3.0"
