generatorName: java
outputDir: ./samples/client/petstore/java/rest-assured-jackson
library: rest-assured
inputSpec: modules/openapi-generator/src/test/resources/experiments.yaml
templateDir: modules/openapi-generator/src/main/resources/Java
additionalProperties:
  serializationLibrary: jackson
  dateLibrary: java8
  performBeanValidation: "true"
  java8: "true"
  useBeanValidation: "true"
  booleanGetterPrefix: is
  artifactId: petstore-rest-assured-jackson
  hideGenerationTimestamp: "true"
