generatorName: jaxrs-jersey
outputDir: samples/server/petstore/jaxrs/jersey1
library: jersey1
inputSpec: modules/openapi-generator/src/test/resources/experiments.yaml
templateDir: modules/openapi-generator/src/main/resources/JavaJaxRS
additionalProperties:
  artifactId: jaxrs-jersey1-server
  hideGenerationTimestamp: "true"
  serverPort: "8082"
