generatorName: jaxrs-resteasy-eap
outputDir: samples/server/petstore/jaxrs-resteasy/eap
inputSpec: modules/openapi-generator/src/test/resources/experiments.yaml
templateDir: modules/openapi-generator/src/main/resources/JavaJaxRS/resteasy/eap
additionalProperties:
  hideGenerationTimestamp: "true"
