generatorName: jaxrs-resteasy
outputDir: samples/server/petstore/jaxrs-resteasy/default
inputSpec: modules/openapi-generator/src/test/resources/experiments.yaml
templateDir: modules/openapi-generator/src/main/resources/JavaJaxRS/resteasy
additionalProperties:
  hideGenerationTimestamp: "true"
  implicitHeadersRegex: api_key
