generatorName: jaxrs-spec
outputDir: samples/server/petstore/jaxrs-spec-jakarta
inputSpec: modules/openapi-generator/src/test/resources/experiments.yaml
templateDir: modules/openapi-generator/src/main/resources/JavaJaxRS/spec
additionalProperties:
  artifactId: jaxrs-spec-petstore-server-jakarta
  serializableModel: "true"
  hideGenerationTimestamp: "true"
  implicitHeadersRegex: (api_key|enum_header_string)
  generateBuilders: "true"
  useJakartaEe: "true"
