generatorName: julia-server
outputDir: samples/server/petstore/julia
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/julia-server
additionalProperties:
  hideGenerationTimestamp: "true"
  packageName: PetStoreServer
