generatorName: kotlin
outputDir: samples/client/petstore/kotlin-array-simple-string-multiplatform
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/kotlin-client
additionalProperties:
  artifactId: kotlin-array-simple-string-multiplatform
  library: multiplatform
