generatorName: kotlin
outputDir: samples/client/petstore/kotlin-json-request-string
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/kotlin-client
additionalProperties:
  requestDateConverter: toString
  artifactId: kotlin-petstore-json-request-string
  parcelizeModels: true
  supportAndroidApiLevel25AndBelow: true
  serializationLibrary: kotlinx_serialization
  enumUnknownDefaultCase: "true"
