generatorName: kotlin
outputDir: samples/client/petstore/kotlin-allOff-discriminator
inputSpec: modules/openapi-generator/src/test/resources/experiments.yaml
templateDir: modules/openapi-generator/src/main/resources/kotlin-client
additionalProperties:
  artifactId: kotlin-allOff-discriminator
  serializableModel: "false"
  dateLibrary: java8
  enumUnknownDefaultCase: true
