generatorName: kotlin
outputDir: samples/client/petstore/kotlin-multiplatform
library: multiplatform
inputSpec: modules/openapi-generator/src/test/resources/experiments.yaml
templateDir: modules/openapi-generator/src/main/resources/kotlin-client
additionalProperties:
  artifactId: kotlin-client-petstore-multiplatform
