generatorName: kotlin
outputDir: samples/client/petstore/kotlin-modelMutable
inputSpec: modules/openapi-generator/src/test/resources/experiments.yaml
templateDir: modules/openapi-generator/src/main/resources/kotlin-client
additionalProperties:
  artifactId: kotlin-modelMutable
  modelMutable: "true"
