generatorName: kotlin-vertx
outputDir: samples/server/petstore/kotlin/vertx
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/kotlin-vertx-server
additionalProperties:
  modelMutable: "false"
