generatorName: ktorm-schema
outputDir: samples/schema/petstore/ktorm
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/ktorm-schema
additionalProperties:
  hideGenerationTimestamp: true
  importModelPackageName: org.openapitools.client.models
