generatorName: lua
outputDir: samples/client/petstore/lua
inputSpec: modules/openapi-generator/src/test/resources/experiments.yaml
templateDir: modules/openapi-generator/src/main/resources/lua
additionalProperties:
  packageName: petstore
