generatorName: mysql-schema
outputDir: samples/schema/petstore/mysql
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/mysql-schema
