generatorName: objc
outputDir: samples/client/petstore/objc/core-data
inputSpec: modules/openapi-generator/src/test/resources/experiments.yaml
templateDir: modules/openapi-generator/src/main/resources/objc
additionalProperties:
  classPrefix: SWG
  podName: SwaggerClient
  coreData: "true"
