generatorName: perl
outputDir: samples/client/petstore/perl
inputSpec: modules/openapi-generator/src/test/resources/experiments.yaml
templateDir: modules/openapi-generator/src/main/resources/perl
additionalProperties:
  hideGenerationTimestamp: "true"
