generatorName: perl
outputDir: samples/client/petstore/perl/deep_module_test
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/perl
additionalProperties:
  moduleName: Something::Deep
  hideGenerationTimestamp: "true"
