generatorName: protobuf-schema
outputDir: samples/config/petstore/protobuf-schema
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/protobuf-schema
additionalProperties:
  packageName: petstore
