generatorName: python-aiohttp
outputDir: samples/server/petstore/python-aiohttp-srclayout
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/python-aiohttp
additionalProperties:
  pythonSrcRoot: src
