generatorName: python
outputDir: samples/openapi3/client/petstore/python-aiohttp
inputSpec: modules/openapi-generator/src/test/resources/experiments.yaml
templateDir: modules/openapi-generator/src/main/resources/python
library: asyncio
additionalProperties:
  packageName: petstore_api
  mapNumberTo: float
