generatorName: r
outputDir: samples/client/petstore/R
inputSpec: modules/openapi-generator/src/test/resources/experiments.yaml
templateDir: modules/openapi-generator/src/main/resources/r
httpUserAgent: PetstoreAgent
additionalProperties:
  packageName: petstore
  exceptionPackage: rlang
  useRlangExceptionHandling: true
  returnExceptionOnFailure: true
  errorObjectType: "ModelApiResponse"
  operationIdNaming: PascalCase #default
  disallowAdditionalPropertiesIfNotPresent: false
