generatorName: r
outputDir: samples/client/petstore/R-httr2
inputSpec: modules/openapi-generator/src/test/resources/experiments.yaml
templateDir: modules/openapi-generator/src/main/resources/r
httpUserAgent: PetstoreAgent
library: httr2
additionalProperties:
  packageName: petstore
  exceptionPackage: rlang
  useRlangExceptionHandling: true
  returnExceptionOnFailure: true
  errorObjectType: "ModelApiResponse"
  operationIdNaming: snake_case
