generatorName: ruby
outputDir: samples/client/petstore/ruby
library: typhoeus
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/ruby-client
additionalProperties:
  gemVersion: 1.0.0
  moduleName: Petstore
  gemName: petstore
  skipFormModel: "true"
strictSpecBehavior: false
