generatorName: rust-server
outputDir: samples/server/petstore/rust-server/output/ops-v3
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/rust-server
generateAliasAsModel: true
additionalProperties:
  hideGenerationTimestamp: "true"
  packageName: ops-v3
