generatorName: rust-server
outputDir: samples/server/petstore/rust-server/output/no-example-v3
inputSpec: modules/openapi-generator/src/test/resources/experiments.yaml
templateDir: modules/openapi-generator/src/main/resources/rust-server
generateAliasAsModel: true
additionalProperties:
  hideGenerationTimestamp: "true"
  packageName: no-example-v3
