generatorName: rust
outputDir: samples/client/petstore/rust/reqwest/petstore-async-middleware
library: reqwest
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/rust
additionalProperties:
  supportAsync: true
  supportMiddleware: true
  supportMultipleResponses: true
  packageName: petstore-reqwest-async-middleware
  useSingleRequestParameter: true
