generatorName: scala-akka-http-server
outputDir: samples/server/petstore/scala-akka-http-server
inputSpec: modules/openapi-generator/src/test/resources/experiments.yaml
templateDir: modules/openapi-generator/src/main/resources/scala-akka-http-server
additionalProperties:
  artifactId: openapi-scala-akka-http-server
