generatorName: scala-akka
outputDir: samples/client/petstore/scala-akka
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/scala-akka-client
additionalProperties:
  artifactId: scala-akka-petstore-client
