generatorName: spring
outputDir: samples/server/petstore/springboot-implicitHeaders
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/JavaSpring
additionalProperties:
  artifactId: springboot-implicitHeaders
  documentationProvider: springfox
  hideGenerationTimestamp: "true"
  implicitHeadersRegex: .*
