generatorName: spring
outputDir: samples/server/petstore/spring-boot-defaultInterface-unhandledException
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/JavaSpring
additionalProperties:
  artifactId: spring-boot-defaultInterface-unhandledException
  hideGenerationTimestamp: true
  java8: true
  interfaceOnly: true
  skipDefaultInterface: true
  unhandledException: true
