generatorName: spring
outputDir: samples/client/petstore/spring-cloud
library: spring-cloud
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/JavaSpring
additionalProperties:
  documentationProvider: springfox
  artifactId: petstore-spring-cloud
  hideGenerationTimestamp: "true"
