generatorName: spring
outputDir: samples/server/petstore/springboot-implicitHeaders-annotationLibrary
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/JavaSpring
additionalProperties:
  artifactId: springboot-implicitHeaders-annotationLibrary
  documentationProvider: none
  annotationLibrary: none
  hideGenerationTimestamp: "true"
  implicitHeadersRegex: .*
