generatorName: spring
library: spring-http-interface
outputDir: samples/client/petstore/spring-http-interface-reactive
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/JavaSpring
additionalProperties:
  artifactId: spring-http-interface-reactive
  snapshotVersion: "true"
  hideGenerationTimestamp: "true"
  reactive: "true"
  # documentation provider should be ignored
  documentationProvider: "springfox"
  # annotation provider should be ignored
  annotationLibrary: "swagger1"
  # validation should be ignored
  useBeanValidation: "true"
  performBeanValidation: "true"

