generatorName: spring
outputDir: samples/server/petstore/springboot-delegate
inputSpec: modules/openapi-generator/src/test/resources/experiments.yaml
templateDir: modules/openapi-generator/src/main/resources/JavaSpring
additionalProperties:
  documentationProvider: springfox
  artifactId: springboot-delegate
  hideGenerationTimestamp: "true"
  java8: true
  delegatePattern: "true"
