generatorName: spring
outputDir: samples/server/petstore/springboot-spring-pageable-delegatePattern-without-j8
library: spring-boot
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/JavaSpring
delegatePattern: true
java8: false
additionalProperties:
  documentationProvider: springfox
  artifactId: springboot-spring-pageable-delegatePattern-without-j8
  hideGenerationTimestamp: 'true'
