generatorName: swift5
outputDir: samples/client/petstore/swift5/nonPublicApi
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/swift5
generateAliasAsModel: true
additionalProperties:
  podAuthors: ""
  podSummary: PetstoreClient
  sortParamsByRequiredFlag: false
  nonPublicApi: true
  projectName: PetstoreClient
  podHomepage: https://github.com/openapitools/openapi-generator
