generatorName: typescript-inversify
outputDir: samples/client/petstore/typescript-inversify
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/typescript-inversify
