generatorName: typescript
outputDir: samples/openapi3/client/petstore/typescript/builds/composed-schemas
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/typescript
additionalProperties:
  npmName: ts-petstore-client
