generatorName: typescript-fetch
outputDir: samples/client/petstore/typescript-fetch/builds/multiple-parameters
inputSpec: modules/openapi-generator/src/test/resources/experiments.yaml
templateDir: modules/openapi-generator/src/main/resources/typescript-fetch
additionalProperties:
  useSingleRequestParameter: false
  snapshot: false
