generatorName: typescript-axios
outputDir: samples/client/petstore/typescript-axios/builds/with-single-request-parameters
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/typescript-axios
additionalProperties:
  useSingleRequestParameter: "true"
