generatorName: typescript-rxjs
outputDir: samples/client/petstore/typescript-rxjs/builds/with-npm-version
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/typescript-rxjs
additionalProperties:
  npmVersion: 1.0.0
  npmName: '@openapitools/typescript-rxjs-petstore'
  npmRepository: https://skimdb.npmjs.com/registry
  snapshot: false
