generatorName: xojo-client
outputDir: samples/client/petstore/xojo/client
inputSpec: modules/openapi-generator/src/test/resources/no-model.yaml
templateDir: modules/openapi-generator/src/main/resources/xojo-client
additionalProperties:
  hideGenerationTimestamp: "true"
  supportsAsync: "true"
