=begin
#Some example

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Petstore::ExampleResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Petstore::ExampleResponse do
  let(:instance) { Petstore::ExampleResponse.new }

  describe 'test an instance of ExampleResponse' do
    it 'should create an instance of ExampleResponse' do
      expect(instance).to be_instance_of(Petstore::ExampleResponse)
    end
  end
end
