/**
* dummy
* dummy
*
* The version of the OpenAPI document: dummy
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.models

import org.openapitools.server.models.OtherObject

import java.io.Serializable
/**
 * dummy
 * @param myOnlyProperty 
 */
data class ExampleResponse(
    val myOnlyProperty: OtherObject? = null
) : Serializable 
{
    companion object {
        private const val serialVersionUID: Long = 123
    }
}

