/**
* dummy
* dummy
*
* The version of the OpenAPI document: dummy
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.models


import java.io.Serializable
/**
 * dummy
 * @param left 
 * @param right 
 */
data class Node(
    val left: Node? = null,
    val right: Node? = null
) : Serializable 
{
    companion object {
        private const val serialVersionUID: Long = 123
    }
}

