# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.dummy200_response_outer_prop_inner_prop import Dummy200ResponseOuterPropInnerProp


class Dummy200ResponseOuterProp(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Dummy200ResponseOuterProp - a model defined in OpenAPI

        inner_prop: The inner_prop of this Dummy200ResponseOuterProp [Optional].
    """

    inner_prop: Optional[Dummy200ResponseOuterPropInnerProp] = Field(alias="innerProp", default=None)

Dummy200ResponseOuterProp.update_forward_refs()
