/**
 * dummy
 * dummy
 *
 * The version of the OpenAPI document: dummy
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model


  /**
   * dummy
   */
case class ExampleResponse(
  emptyString: Option[String] = None,
  numberString: Option[String] = None,
  boolString: Option[String] = None,
  nullString: Option[String] = None,
  aBool: Option[Boolean] = None,
  zero: Option[Int] = None
)

