# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ExampleResponse
dummy

    ExampleResponse(;
        myOnlyProperty=nothing,
    )

    - myOnlyProperty::Vector{Float64}
"""
Base.@kwdef mutable struct ExampleResponse <: OpenAPI.APIModel
    myOnlyProperty::Union{Nothing, Vector{Float64}} = nothing

    function ExampleResponse(myOnlyProperty, )
        OpenAPI.validate_property(ExampleResponse, Symbol("myOnlyProperty"), myOnlyProperty)
        return new(myOnlyProperty, )
    end
end # type ExampleResponse

const _property_types_ExampleResponse = Dict{Symbol,String}(Symbol("myOnlyProperty")=>"Vector{Float64}", )
OpenAPI.property_type(::Type{ ExampleResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ExampleResponse[name]))}

function check_required(o::ExampleResponse)
    true
end

function OpenAPI.validate_property(::Type{ ExampleResponse }, name::Symbol, val)
    if name === Symbol("myOnlyProperty")
        OpenAPI.validate_param(name, "ExampleResponse", :uniqueItems, val, true)
    end
end
