//
// PrefixDummy200ResponseOuterPropInnerPropSuffix.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PrefixDummy200ResponseOuterPropInnerPropSuffix: Codable, JSONEncodable, Hashable {

    public var myBool: Bool?

    public init(myBool: Bool? = nil) {
        self.myBool = myBool
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case myBool
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(myBool, forKey: .myBool)
    }
}

