//
// PrefixExampleResponseSuffix.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** dummy */
public struct PrefixExampleResponseSuffix: Codable, JSONEncodable, Hashable {

    public var myOnlyProperty: Set<Double>?

    public init(myOnlyProperty: Set<Double>? = nil) {
        self.myOnlyProperty = myOnlyProperty
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case myOnlyProperty
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(myOnlyProperty, forKey: .myOnlyProperty)
    }
}

