{-
   Some example
   No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

   The version of the OpenAPI document: 0.0.1

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Default exposing
    ( retrieveSomething
    )

import Api
import Api.Data exposing (..)
import Dict
import Http
import Json.Decode
import Json.Encode

{-| get some object
-}
retrieveSomething : Api.Request (List Float)
retrieveSomething =
    Api.request
        "GET"
        "/example/someMethod"
        []
        []
        []
        Nothing
        (Json.Decode.list Json.Decode.float)

