/*
 * OpenAPI Petstore
 *
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing FormatTest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FormatTestTests
    {
        // TODO uncomment below to declare an instance variable for FormatTest
        //private FormatTest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FormatTest
            //instance = new FormatTest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FormatTest
        /// </summary>
        [Test]
        public void FormatTestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" FormatTest
            //Assert.IsInstanceOf(typeof(FormatTest), instance);
        }


        /// <summary>
        /// Test the property 'Integer'
        /// </summary>
        [Test]
        public void IntegerTest()
        {
            // TODO unit test for the property 'Integer'
        }
        /// <summary>
        /// Test the property 'Int32'
        /// </summary>
        [Test]
        public void Int32Test()
        {
            // TODO unit test for the property 'Int32'
        }
        /// <summary>
        /// Test the property 'Int64'
        /// </summary>
        [Test]
        public void Int64Test()
        {
            // TODO unit test for the property 'Int64'
        }
        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Test]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }
        /// <summary>
        /// Test the property 'VarFloat'
        /// </summary>
        [Test]
        public void VarFloatTest()
        {
            // TODO unit test for the property 'VarFloat'
        }
        /// <summary>
        /// Test the property 'VarDouble'
        /// </summary>
        [Test]
        public void VarDoubleTest()
        {
            // TODO unit test for the property 'VarDouble'
        }
        /// <summary>
        /// Test the property 'VarDecimal'
        /// </summary>
        [Test]
        public void VarDecimalTest()
        {
            // TODO unit test for the property 'VarDecimal'
        }
        /// <summary>
        /// Test the property 'VarString'
        /// </summary>
        [Test]
        public void VarStringTest()
        {
            // TODO unit test for the property 'VarString'
        }
        /// <summary>
        /// Test the property 'VarByte'
        /// </summary>
        [Test]
        public void VarByteTest()
        {
            // TODO unit test for the property 'VarByte'
        }
        /// <summary>
        /// Test the property 'Binary'
        /// </summary>
        [Test]
        public void BinaryTest()
        {
            // TODO unit test for the property 'Binary'
        }
        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Test]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'DateTime'
        /// </summary>
        [Test]
        public void DateTimeTest()
        {
            // TODO unit test for the property 'DateTime'
        }
        /// <summary>
        /// Test the property 'Uuid'
        /// </summary>
        [Test]
        public void UuidTest()
        {
            // TODO unit test for the property 'Uuid'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Test]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'PatternWithDigits'
        /// </summary>
        [Test]
        public void PatternWithDigitsTest()
        {
            // TODO unit test for the property 'PatternWithDigits'
        }
        /// <summary>
        /// Test the property 'PatternWithDigitsAndDelimiter'
        /// </summary>
        [Test]
        public void PatternWithDigitsAndDelimiterTest()
        {
            // TODO unit test for the property 'PatternWithDigitsAndDelimiter'
        }

    }

}
