#
# dummy
# dummy
# Version: dummy
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSPetstore' -name 'PSDummy200ResponseOuterProp' {
    Context 'PSDummy200ResponseOuterProp' {
        It 'Initialize-PSDummy200ResponseOuterProp' {
            # a simple test to create an object
            #$NewObject = Initialize-PSDummy200ResponseOuterProp -InnerProp "TEST_VALUE"
            #$NewObject | Should -BeOfType Dummy200ResponseOuterProp
            #$NewObject.property | Should -Be 0
        }
    }
}
