/*
 * dummy
 * dummy
 *
 * The version of the OpenAPI document: dummy
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.client.model.Dummy200ResponseOuterProp;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Dummy200Response
 */
public class Dummy200ResponseTest {
    private final Dummy200Response model = new Dummy200Response();

    /**
     * Model tests for Dummy200Response
     */
    @Test
    public void testDummy200Response() {
        // TODO: test Dummy200Response
    }

    /**
     * Test the property 'outerProp'
     */
    @Test
    public void outerPropTest() {
        // TODO: test outerProp
    }

}
