/**
 * dummy
 * dummy
 *
 * The version of the OpenAPI document: dummy
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Dummy200ResponseOuterPropInnerProp from './Dummy200ResponseOuterPropInnerProp';

/**
 * The Dummy200ResponseOuterProp model module.
 * @module model/Dummy200ResponseOuterProp
 * @version dummy
 */
class Dummy200ResponseOuterProp {
    /**
     * Constructs a new <code>Dummy200ResponseOuterProp</code>.
     * @alias module:model/Dummy200ResponseOuterProp
     */
    constructor() { 
        
        Dummy200ResponseOuterProp.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Dummy200ResponseOuterProp</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Dummy200ResponseOuterProp} obj Optional instance to populate.
     * @return {module:model/Dummy200ResponseOuterProp} The populated <code>Dummy200ResponseOuterProp</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Dummy200ResponseOuterProp();

            if (data.hasOwnProperty('innerProp')) {
                obj['innerProp'] = Dummy200ResponseOuterPropInnerProp.constructFromObject(data['innerProp']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Dummy200ResponseOuterProp</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Dummy200ResponseOuterProp</code>.
     */
    static validateJSON(data) {
        // validate the optional field `innerProp`
        if (data['innerProp']) { // data not null
          Dummy200ResponseOuterPropInnerProp.validateJSON(data['innerProp']);
        }

        return true;
    }


}



/**
 * @member {module:model/Dummy200ResponseOuterPropInnerProp} innerProp
 */
Dummy200ResponseOuterProp.prototype['innerProp'] = undefined;






export default Dummy200ResponseOuterProp;

