/**
 * dummy
 * dummy
 *
 * The version of the OpenAPI document: dummy
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Node model module.
 * @module model/Node
 * @version dummy
 */
class Node {
    /**
     * Constructs a new <code>Node</code>.
     * dummy
     * @alias module:model/Node
     */
    constructor() { 
        
        Node.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Node</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Node} obj Optional instance to populate.
     * @return {module:model/Node} The populated <code>Node</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Node();

            if (data.hasOwnProperty('left')) {
                obj['left'] = Node.constructFromObject(data['left']);
            }
            if (data.hasOwnProperty('right')) {
                obj['right'] = Node.constructFromObject(data['right']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Node</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Node</code>.
     */
    static validateJSON(data) {
        // validate the optional field `left`
        if (data['left']) { // data not null
          Node.validateJSON(data['left']);
        }
        // validate the optional field `right`
        if (data['right']) { // data not null
          Node.validateJSON(data['right']);
        }

        return true;
    }


}



/**
 * @member {module:model/Node} left
 */
Node.prototype['left'] = undefined;

/**
 * @member {module:model/Node} right
 */
Node.prototype['right'] = undefined;






export default Node;

