/**
 * dummy
 * dummy
 *
 * The version of the OpenAPI document: dummy
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ExampleResponse from './ExampleResponse';

/**
 * The OtherObject model module.
 * @module model/OtherObject
 * @version dummy
 */
class OtherObject {
    /**
     * Constructs a new <code>OtherObject</code>.
     * dummy
     * @alias module:model/OtherObject
     */
    constructor() { 
        
        OtherObject.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OtherObject</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OtherObject} obj Optional instance to populate.
     * @return {module:model/OtherObject} The populated <code>OtherObject</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OtherObject();

            if (data.hasOwnProperty('myOnlyProperty2')) {
                obj['myOnlyProperty2'] = ExampleResponse.constructFromObject(data['myOnlyProperty2']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OtherObject</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OtherObject</code>.
     */
    static validateJSON(data) {
        // validate the optional field `myOnlyProperty2`
        if (data['myOnlyProperty2']) { // data not null
          ExampleResponse.validateJSON(data['myOnlyProperty2']);
        }

        return true;
    }


}



/**
 * @member {module:model/ExampleResponse} myOnlyProperty2
 */
OtherObject.prototype['myOnlyProperty2'] = undefined;






export default OtherObject;

