//
// Dummy200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct Dummy200Response: Codable, JSONEncodable, Hashable {

    internal var outerProp: Dummy200ResponseOuterProp?

    internal init(outerProp: Dummy200ResponseOuterProp? = nil) {
        self.outerProp = outerProp
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case outerProp
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(outerProp, forKey: .outerProp)
    }
}

