//
// OtherObject.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** dummy */
internal struct OtherObject: Codable, JSONEncodable, Hashable {

    internal var myOnlyProperty2: ExampleResponse?

    internal init(myOnlyProperty2: ExampleResponse? = nil) {
        self.myOnlyProperty2 = myOnlyProperty2
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case myOnlyProperty2
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(myOnlyProperty2, forKey: .myOnlyProperty2)
    }
}

