/*
 * dummy
 *
 * dummy
 *
 * API version: dummy
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package petstoreserver


import (
	"encoding/json"
)



// Node - dummy
type Node struct {

	Left Node `json:"left,omitempty"`

	Right Node `json:"right,omitempty"`
}

// UnmarshalJSON sets *m to a copy of data while respecting defaults if specified.
func (m *Node) UnmarshalJSON(data []byte) error {

	type Alias Node // To avoid infinite recursion
    return json.Unmarshal(data, (*Alias)(m))
}

// AssertNodeRequired checks if the required fields are not zero-ed
func AssertNodeRequired(obj Node) error {
	if err := AssertNodeRequired(obj.Left); err != nil {
		return err
	}
	if err := AssertNodeRequired(obj.Right); err != nil {
		return err
	}
	return nil
}

// AssertNodeConstraints checks if the values respects the defined constraints
func AssertNodeConstraints(obj Node) error {
	return nil
}
