{-
   Some example

   dummy description

   OpenAPI Version: 3.0.1
   Some example API version: 0.0.1
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : SomeExample.API
-}

module SomeExample.API
  ( module SomeExample.API.ApiDefault
  ) where

import SomeExample.API.ApiDefault