/**
 * dummy
 * dummy
 *
 * The version of the OpenAPI document: dummy
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Dummy200ResponseOuterProp } from './dummy200ResponseOuterProp';

export class Dummy200Response {
    'outerProp'?: Dummy200ResponseOuterProp;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "outerProp",
            "baseName": "outerProp",
            "type": "Dummy200ResponseOuterProp"
        }    ];

    static getAttributeTypeMap() {
        return Dummy200Response.attributeTypeMap;
    }
}

