/**
 * dummy
 * dummy
 *
 * The version of the OpenAPI document: dummy
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { OtherObject } from './otherObject';

/**
* dummy
*/
export class ExampleResponse {
    'myOnlyProperty'?: OtherObject;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "myOnlyProperty",
            "baseName": "myOnlyProperty",
            "type": "OtherObject"
        }    ];

    static getAttributeTypeMap() {
        return ExampleResponse.attributeTypeMap;
    }
}

