/**
* dummy
* dummy
*
* The version of the OpenAPI document: dumy
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.api.model


        
import com.google.gson.annotations.SerializedName
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
/**
 * dummy
 * @param myOnlyProperty 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
data class ExampleResponse (
    val myOnlyProperty: kotlin.collections.Set<java.math.BigDecimal>? = null
) {

}

