

#import "SWGDummy200ResponseOuterPropInnerPropManagedObjectBuilder.h"

/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

@implementation SWGDummy200ResponseOuterPropInnerPropManagedObjectBuilder

-(instancetype)init {
    self = [super init];
    if (self != nil) {
    }
    return self;
}

-(SWGDummy200ResponseOuterPropInnerPropManagedObject*)createNewSWGDummy200ResponseOuterPropInnerPropManagedObjectInContext:(NSManagedObjectContext*)context {
    SWGDummy200ResponseOuterPropInnerPropManagedObject *managedObject = [NSEntityDescription insertNewObjectForEntityForName:NSStringFromClass([SWGDummy200ResponseOuterPropInnerPropManagedObject class]) inManagedObjectContext:context];
    return managedObject;
}

-(SWGDummy200ResponseOuterPropInnerPropManagedObject*)SWGDummy200ResponseOuterPropInnerPropManagedObjectFromSWGDummy200ResponseOuterPropInnerProp:(SWGDummy200ResponseOuterPropInnerProp*)object context:(NSManagedObjectContext*)context {
    SWGDummy200ResponseOuterPropInnerPropManagedObject* newSWGDummy200ResponseOuterPropInnerProp = [self createNewSWGDummy200ResponseOuterPropInnerPropManagedObjectInContext:context];
    [self updateSWGDummy200ResponseOuterPropInnerPropManagedObject:newSWGDummy200ResponseOuterPropInnerProp withSWGDummy200ResponseOuterPropInnerProp:object];
    return newSWGDummy200ResponseOuterPropInnerProp;
}

-(void)updateSWGDummy200ResponseOuterPropInnerPropManagedObject:(SWGDummy200ResponseOuterPropInnerPropManagedObject*)managedObject withSWGDummy200ResponseOuterPropInnerProp:(SWGDummy200ResponseOuterPropInnerProp*)object {
    if(!managedObject || !object) {
        return;
    }
    NSManagedObjectContext* context = managedObject.managedObjectContext;
    managedObject.myBool = [object.myBool copy];

}

-(SWGDummy200ResponseOuterPropInnerProp*)SWGDummy200ResponseOuterPropInnerPropFromSWGDummy200ResponseOuterPropInnerPropManagedObject:(SWGDummy200ResponseOuterPropInnerPropManagedObject*)obj {
    if(!obj) {
        return nil;
    }
    SWGDummy200ResponseOuterPropInnerProp* newSWGDummy200ResponseOuterPropInnerProp = [[SWGDummy200ResponseOuterPropInnerProp alloc] init];
    [self updateSWGDummy200ResponseOuterPropInnerProp:newSWGDummy200ResponseOuterPropInnerProp withSWGDummy200ResponseOuterPropInnerPropManagedObject:obj];
    return newSWGDummy200ResponseOuterPropInnerProp;
}

-(void)updateSWGDummy200ResponseOuterPropInnerProp:(SWGDummy200ResponseOuterPropInnerProp*)newSWGDummy200ResponseOuterPropInnerProp withSWGDummy200ResponseOuterPropInnerPropManagedObject:(SWGDummy200ResponseOuterPropInnerPropManagedObject*)obj {
    newSWGDummy200ResponseOuterPropInnerProp.myBool = [obj.myBool copy];
}

@end
