#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>

/**
* Some example
* dummy description
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/




NS_ASSUME_NONNULL_BEGIN

@interface SWGExampleResponseManagedObject : NSManagedObject


@property (nullable, nonatomic, retain) NSArray<NSNumber*>* myOnlyProperty;
@end

@interface SWGExampleResponseManagedObject (GeneratedAccessors)

@end


NS_ASSUME_NONNULL_END
