#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* dummy
* dummy
*
* The version of the OpenAPI document: dumy
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "SWGSet.h"
@protocol SWGSet;
@class SWGSet;



@protocol SWGExampleResponse
@end

@interface SWGExampleResponse : SWGObject


@property(nonatomic) SWGSet<NSNumber*>* myOnlyProperty;

@end
