#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>

#import "SWGExampleResponseManagedObjectBuilder.h"

#import "SWGOtherObjectManagedObject.h"
#import "SWGOtherObject.h"

/**
* dummy
* dummy
*
* The version of the OpenAPI document: dummy
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


@interface SWGOtherObjectManagedObjectBuilder : NSObject

@property (nonatomic, strong) SWGExampleResponseManagedObjectBuilder * myOnlyProperty2Builder;


-(SWGOtherObjectManagedObject*)createNewSWGOtherObjectManagedObjectInContext:(NSManagedObjectContext*)context;

-(SWGOtherObjectManagedObject*)SWGOtherObjectManagedObjectFromSWGOtherObject:(SWGOtherObject*)object context:(NSManagedObjectContext*)context;

-(void)updateSWGOtherObjectManagedObject:(SWGOtherObjectManagedObject*)object withSWGOtherObject:(SWGOtherObject*)object2;

-(SWGOtherObject*)SWGOtherObjectFromSWGOtherObjectManagedObject:(SWGOtherObjectManagedObject*)obj;

-(void)updateSWGOtherObject:(SWGOtherObject*)object withSWGOtherObjectManagedObject:(SWGOtherObjectManagedObject*)object2;

@end
