# coding: utf-8

"""
    OpenAPI Petstore

    dummy  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class Param0Def(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            
            
            class param0Field(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['Param1Def']:
                        return Param1Def
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['Param1Def'], typing.List['Param1Def']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'param0Field':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'Param1Def':
                    return super().__getitem__(i)
            __annotations__ = {
                "param0Field": param0Field,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["param0Field"]) -> MetaOapg.properties.param0Field: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["param0Field", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["param0Field"]) -> typing.Union[MetaOapg.properties.param0Field, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["param0Field", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        param0Field: typing.Union[MetaOapg.properties.param0Field, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Param0Def':
        return super().__new__(
            cls,
            *_args,
            param0Field=param0Field,
            _configuration=_configuration,
            **kwargs,
        )

from openapi_client.model.param1_def import Param1Def
