// tslint:disable
/**
 * dummy
 * dummy
 *
 * The version of the OpenAPI document: dummy
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    Dummy200ResponseOuterProp,
} from './';

/**
 * @export
 * @interface Dummy200Response
 */
export interface Dummy200Response {
    /**
     * @type {Dummy200ResponseOuterProp}
     * @memberof Dummy200Response
     */
    outerProp?: Dummy200ResponseOuterProp;
}
