{-
   

   dummy description

   OpenAPI Version: 3.0.0
    API version: 
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : OpenAPI.Logging
Logging functions
-}
{-# LANGUAGE CPP #-}

#ifdef USE_KATIP

module OpenAPI.Logging
  ( module OpenAPI.LoggingKatip
  ) where

import OpenAPI.LoggingKatip

#else

module OpenAPI.Logging
  ( module OpenAPI.LoggingMonadLogger
  ) where

import OpenAPI.LoggingMonadLogger

#endif
