/**
 * dummy
 * dummy
 *
 * OpenAPI spec version: dummy
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* dummy
*/
export class ExampleResponse {
    'emptyString'?: string;
    'numberString'?: string;
    'boolString'?: string;
    'nullString'?: string;
    'aBool'?: boolean;
    'zero'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "emptyString",
            "baseName": "emptyString",
            "type": "string",
            "format": ""
        },
        {
            "name": "numberString",
            "baseName": "numberString",
            "type": "string",
            "format": ""
        },
        {
            "name": "boolString",
            "baseName": "boolString",
            "type": "string",
            "format": ""
        },
        {
            "name": "nullString",
            "baseName": "nullString",
            "type": "string",
            "format": ""
        },
        {
            "name": "aBool",
            "baseName": "aBool",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "zero",
            "baseName": "zero",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ExampleResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

