=begin
#dummy

#dummy

The version of the OpenAPI document: dummy

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for DynamicServers::OtherObject
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe DynamicServers::OtherObject do
  let(:instance) { DynamicServers::OtherObject.new }

  describe 'test an instance of OtherObject' do
    it 'should create an instance of OtherObject' do
      expect(instance).to be_instance_of(DynamicServers::OtherObject)
    end
  end
  describe 'test attribute "my_only_property2"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
