/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models.room

import androidx.room.Entity
import androidx.room.Ignore
import androidx.room.PrimaryKey
import org.openapitools.client.models.*


@Entity(tableName = "Dummy200ResponseOuterProp")
/**
* Room model for 
* @param innerProp 
*/
data class Dummy200ResponseOuterPropRoomModel (
    @PrimaryKey(autoGenerate = true) var roomTableId: Int,
    
    var innerProp: Dummy200ResponseOuterPropInnerProp? = null,
    
    ) {

    companion object { }

        fun toApiModel(): Dummy200ResponseOuterProp = Dummy200ResponseOuterProp(
        innerProp = this.innerProp,
        )
}
