/**
 * 
 * dummy description
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.api

import org.openapitools.client.core.JsonSupport._
import sttp.client3._
import sttp.model.Method

object DefaultApi {

def apply(baseUrl: String = "http://localhost") = new DefaultApi(baseUrl)
}

class DefaultApi(baseUrl: String) {

  /**
   * get some object
   * 
   * Expected answers:
   *   code 200 : Int (The response with results)
   */
  def retrieveSomething(
): Request[Either[ResponseException[String, Exception], Int], Any] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/example/someMethod")
      .contentType("application/json")
      .response(asJson[Int])

}
