name: PetstoreClient
targets:
  PetstoreClient:
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
    sources: [Sources]
    info:
      path: ./Info.plist
      version: dumy
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
