/*
 * dummy
 *
 * dummy
 *
 * The version of the OpenAPI document: dummy
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Dummy200ResponseOuterProp : IEquatable<Dummy200ResponseOuterProp>
    {
        /// <summary>
        /// Gets or Sets InnerProp
        /// </summary>
        [DataMember(Name="innerProp", EmitDefaultValue=false)]
        public Dummy200ResponseOuterPropInnerProp InnerProp { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Dummy200ResponseOuterProp {\n");
            sb.Append("  InnerProp: ").Append(InnerProp).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            var options = new JsonSerializerOptions
            {
                WriteIndented = true
            };

            return JsonSerializer.Serialize(this, options);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Dummy200ResponseOuterProp)obj);
        }

        /// <summary>
        /// Returns true if Dummy200ResponseOuterProp instances are equal
        /// </summary>
        /// <param name="other">Instance of Dummy200ResponseOuterProp to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Dummy200ResponseOuterProp other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    InnerProp == other.InnerProp ||
                    InnerProp != null &&
                    InnerProp.Equals(other.InnerProp)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (InnerProp != null)
                    hashCode = hashCode * 59 + InnerProp.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Dummy200ResponseOuterProp left, Dummy200ResponseOuterProp right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Dummy200ResponseOuterProp left, Dummy200ResponseOuterProp right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
