/**
 * dummy
 * dummy
 *
 * The version of the OpenAPI document: dummy
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Dummy_200_response_outerProp.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Dummy_200_response_outerProp_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Dummy_200_response_outerProp_H_


#include "CppRestPetstoreClient/ModelBase.h"

#include "CppRestPetstoreClient/model/Dummy_200_response_outerProp_innerProp.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class Dummy_200_response_outerProp_innerProp;

/// <summary>
/// 
/// </summary>
class  Dummy_200_response_outerProp
    : public ModelBase
{
public:
    Dummy_200_response_outerProp();
    virtual ~Dummy_200_response_outerProp();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Dummy_200_response_outerProp members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Dummy_200_response_outerProp_innerProp> getInnerProp() const;
    bool innerPropIsSet() const;
    void unsetInnerProp();

    void setInnerProp(const std::shared_ptr<Dummy_200_response_outerProp_innerProp>& value);


protected:
    std::shared_ptr<Dummy_200_response_outerProp_innerProp> m_InnerProp;
    bool m_InnerPropIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Dummy_200_response_outerProp_H_ */
