//
// Dummy200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Dummy200Response: Codable, JSONEncodable {

    public var outerProp: Dummy200ResponseOuterProp?

    public init(outerProp: Dummy200ResponseOuterProp? = nil) {
        self.outerProp = outerProp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case outerProp
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(outerProp, forKey: .outerProp)
    }
}

