openapi: 3.0.1
info:
  description: dummy description
  title: Some example
  version: 0.0.1
servers:
- url: /
paths:
  /example/someMethod:
    get:
      description: get some object
      operationId: retrieveSomething
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExampleResponse'
          description: The response with results
components:
  schemas:
    ExampleResponse:
      example:
        myOnlyProperty:
        - true
        - true
      properties:
        myOnlyProperty:
          items:
            type: boolean
          type: array
      type: object

