# #dummy
#
##dummy
#
#The version of the OpenAPI document: dummy
#
#Generated by: https://openapi-generator.tech
#OpenAPI Generator version: 7.0.0-SNAPSHOT
#

require "uri"

module Petstore
  class DefaultApi
    property api_client : ApiClient

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # dummy
    # @return [Dummy200Response]
    def dummy()
      data, _status_code, _headers = dummy_with_http_info()
      data
    end

    # dummy
    # @return [Array<(Dummy200Response, Integer, Hash)>] Dummy200Response data, response status code and response headers
    def dummy_with_http_info()
      if @api_client.config.debugging
        Log.debug {"Calling API: DefaultApi.dummy ..."}
      end
      # resource path
      local_var_path = "/example/someMethod"

      # query parameters
      query_params = Hash(String, String).new

      # header parameters
      header_params = Hash(String, String).new
      # HTTP header "Accept" (if needed)
      header_params["Accept"] = @api_client.select_header_accept(["*/*"])

      # form parameters
      form_params = Hash(Symbol, (String | ::File)).new

      # http body (model)
      post_body = nil

      # return_type
      return_type = "Dummy200Response"

      # auth_names
      auth_names = [] of String

      data, status_code, headers = @api_client.call_api(:GET,
                                                        local_var_path,
                                                        :"DefaultApi.dummy",
                                                        return_type,
                                                        post_body,
                                                        auth_names,
                                                        header_params,
                                                        query_params,
                                                        form_params)
      if @api_client.config.debugging
        Log.debug {"API called: DefaultApi#dummy\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"}
      end
      return Dummy200Response.from_json(data), status_code, headers
    end
  end
end
