/**
 * dummy
 * dummy
 *
 * The version of the OpenAPI document: dummy
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package org.openapitools.server.models

import org.openapitools.server.models.ExampleResponse
import com.fasterxml.jackson.annotation.JsonProperty
/**
 * dummy
 *
 * @param myOnlyProperty2 
 */


data class OtherObject (


    @JsonProperty("myOnlyProperty2")
    val myOnlyProperty2: ExampleResponse? = null

)

