/**
* dummy
* dummy
*
* The version of the OpenAPI document: dumy
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server

import io.ktor.resources.*
import kotlinx.serialization.*
import org.openapitools.server.models.*

object Paths {
    /**
     * dummy
     */
    @Serializable @Resource("/example/someMethod") class dummy

}
