<?php
declare(strict_types=1);

namespace App;

use Articus\DataTransfer as DT;
use OpenAPIGenerator\APIClient as OAGAC;
use Psr\Http\Client\ClientExceptionInterface;
use Psr\Http\Message\ResponseInterface;

/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 
 */
class ApiClient extends OAGAC\AbstractApiClient
{
    //region exampleSomeMethodGet
    /**
     * @param string $responseMediaType
     * @return ResponseInterface
     * @throws ClientExceptionInterface
     * @throws DT\Exception\InvalidData
     */
    public function exampleSomeMethodGetRaw(
        string $responseMediaType = '/'
    ): ResponseInterface
    {
        $request = $this->createRequest('GET', '/example/someMethod', [], []);
        $request = $this->addAcceptHeader($request, $responseMediaType);
        return $this->httpClient->sendRequest($request);
    }

    /**
     * @param string $responseMediaType
     * @return array
     * @throws ClientExceptionInterface
     * @throws DT\Exception\InvalidData
     * @throws OAGAC\Exception\InvalidResponseBodySchema
     */
    public function exampleSomeMethodGet(
        string $responseMediaType = '/'
    ): array
    {
        $response = $this->exampleSomeMethodGetRaw($responseMediaType);
        $responseContent = null;
        switch ($response->getStatusCode())
        {
            case 200:
                /*  */
                $responseContent = new \App\DTO\ExampleResponse();
                break;
        }
        $this->parseBody($response, $responseContent);
        return [$responseContent, $response->getHeaders(), $response->getStatusCode(), $response->getReasonPhrase()];
    }

    /**
     * @param string $responseMediaType
     * @return \App\DTO\ExampleResponse
     * @throws ClientExceptionInterface
     * @throws DT\Exception\InvalidData
     * @throws OAGAC\Exception\InvalidResponseBodySchema
     * @throws OAGAC\Exception\UnsuccessfulResponse
     */
    public function exampleSomeMethodGetResult(
        string $responseMediaType = '/'
    ): \App\DTO\ExampleResponse
    {
        return $this->getSuccessfulContent(...$this->exampleSomeMethodGet($responseMediaType));
    }
    //endregion
}

