/*
 * dummy
 * dummy
 *
 * The version of the OpenAPI document: dummy
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * dummy
 */
@JsonPropertyOrder({
  ExampleResponse.JSON_PROPERTY_EMPTY_STRING,
  ExampleResponse.JSON_PROPERTY_NUMBER_STRING,
  ExampleResponse.JSON_PROPERTY_BOOL_STRING,
  ExampleResponse.JSON_PROPERTY_NULL_STRING,
  ExampleResponse.JSON_PROPERTY_A_BOOL,
  ExampleResponse.JSON_PROPERTY_ZERO
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ExampleResponse {
  public static final String JSON_PROPERTY_EMPTY_STRING = "emptyString";
  private String emptyString = "";

  public static final String JSON_PROPERTY_NUMBER_STRING = "numberString";
  private String numberString = "42";

  public static final String JSON_PROPERTY_BOOL_STRING = "boolString";
  private String boolString = "false";

  public static final String JSON_PROPERTY_NULL_STRING = "nullString";
  private String nullString = "null";

  public static final String JSON_PROPERTY_A_BOOL = "aBool";
  private Boolean aBool = false;

  public static final String JSON_PROPERTY_ZERO = "zero";
  private Integer zero = 0;

  public ExampleResponse() { 
  }

  public ExampleResponse emptyString(String emptyString) {
    this.emptyString = emptyString;
    return this;
  }

   /**
   * Get emptyString
   * @return emptyString
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EMPTY_STRING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEmptyString() {
    return emptyString;
  }


  @JsonProperty(JSON_PROPERTY_EMPTY_STRING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmptyString(String emptyString) {
    this.emptyString = emptyString;
  }


  public ExampleResponse numberString(String numberString) {
    this.numberString = numberString;
    return this;
  }

   /**
   * Get numberString
   * @return numberString
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NUMBER_STRING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNumberString() {
    return numberString;
  }


  @JsonProperty(JSON_PROPERTY_NUMBER_STRING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNumberString(String numberString) {
    this.numberString = numberString;
  }


  public ExampleResponse boolString(String boolString) {
    this.boolString = boolString;
    return this;
  }

   /**
   * Get boolString
   * @return boolString
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BOOL_STRING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBoolString() {
    return boolString;
  }


  @JsonProperty(JSON_PROPERTY_BOOL_STRING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBoolString(String boolString) {
    this.boolString = boolString;
  }


  public ExampleResponse nullString(String nullString) {
    this.nullString = nullString;
    return this;
  }

   /**
   * Get nullString
   * @return nullString
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NULL_STRING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNullString() {
    return nullString;
  }


  @JsonProperty(JSON_PROPERTY_NULL_STRING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNullString(String nullString) {
    this.nullString = nullString;
  }


  public ExampleResponse aBool(Boolean aBool) {
    this.aBool = aBool;
    return this;
  }

   /**
   * Get aBool
   * @return aBool
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_A_BOOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getaBool() {
    return aBool;
  }


  @JsonProperty(JSON_PROPERTY_A_BOOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setaBool(Boolean aBool) {
    this.aBool = aBool;
  }


  public ExampleResponse zero(Integer zero) {
    this.zero = zero;
    return this;
  }

   /**
   * Get zero
   * @return zero
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ZERO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getZero() {
    return zero;
  }


  @JsonProperty(JSON_PROPERTY_ZERO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setZero(Integer zero) {
    this.zero = zero;
  }


  /**
   * Return true if this ExampleResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExampleResponse exampleResponse = (ExampleResponse) o;
    return Objects.equals(this.emptyString, exampleResponse.emptyString) &&
        Objects.equals(this.numberString, exampleResponse.numberString) &&
        Objects.equals(this.boolString, exampleResponse.boolString) &&
        Objects.equals(this.nullString, exampleResponse.nullString) &&
        Objects.equals(this.aBool, exampleResponse.aBool) &&
        Objects.equals(this.zero, exampleResponse.zero);
  }

  @Override
  public int hashCode() {
    return Objects.hash(emptyString, numberString, boolString, nullString, aBool, zero);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExampleResponse {\n");
    sb.append("    emptyString: ").append(toIndentedString(emptyString)).append("\n");
    sb.append("    numberString: ").append(toIndentedString(numberString)).append("\n");
    sb.append("    boolString: ").append(toIndentedString(boolString)).append("\n");
    sb.append("    nullString: ").append(toIndentedString(nullString)).append("\n");
    sb.append("    aBool: ").append(toIndentedString(aBool)).append("\n");
    sb.append("    zero: ").append(toIndentedString(zero)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `emptyString` to the URL query string
    if (getEmptyString() != null) {
      joiner.add(String.format("%semptyString%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getEmptyString()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `numberString` to the URL query string
    if (getNumberString() != null) {
      joiner.add(String.format("%snumberString%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getNumberString()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `boolString` to the URL query string
    if (getBoolString() != null) {
      joiner.add(String.format("%sboolString%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getBoolString()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `nullString` to the URL query string
    if (getNullString() != null) {
      joiner.add(String.format("%snullString%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getNullString()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `aBool` to the URL query string
    if (getaBool() != null) {
      joiner.add(String.format("%saBool%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getaBool()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `zero` to the URL query string
    if (getZero() != null) {
      joiner.add(String.format("%szero%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getZero()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

