/*
 * dummy
 * dummy
 *
 * The version of the OpenAPI document: dummy
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.client.model.ExampleResponse;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for OtherObject
 */
public class OtherObjectTest {
    private final OtherObject model = new OtherObject();

    /**
     * Model tests for OtherObject
     */
    @Test
    public void testOtherObject() {
        // TODO: test OtherObject
    }

    /**
     * Test the property 'myOnlyProperty2'
     */
    @Test
    public void myOnlyProperty2Test() {
        // TODO: test myOnlyProperty2
    }

}
