/*
 * dummy
 * dummy
 *
 * The version of the OpenAPI document: dummy
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import org.openapitools.client.JSON;


/**
 * Dummy200ResponseOuterPropInnerProp
 */
@JsonPropertyOrder({
  Dummy200ResponseOuterPropInnerProp.JSON_PROPERTY_MY_BOOL
})
@JsonTypeName("dummy_200_response_outerProp_innerProp")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Dummy200ResponseOuterPropInnerProp {
  public static final String JSON_PROPERTY_MY_BOOL = "myBool";
  private Boolean myBool;

  public Dummy200ResponseOuterPropInnerProp() { 
  }

  public Dummy200ResponseOuterPropInnerProp myBool(Boolean myBool) {
    this.myBool = myBool;
    return this;
  }

   /**
   * Get myBool
   * @return myBool
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MY_BOOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getMyBool() {
    return myBool;
  }


  @JsonProperty(JSON_PROPERTY_MY_BOOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMyBool(Boolean myBool) {
    this.myBool = myBool;
  }


  /**
   * Return true if this dummy_200_response_outerProp_innerProp object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Dummy200ResponseOuterPropInnerProp dummy200ResponseOuterPropInnerProp = (Dummy200ResponseOuterPropInnerProp) o;
    return Objects.equals(this.myBool, dummy200ResponseOuterPropInnerProp.myBool);
  }

  @Override
  public int hashCode() {
    return Objects.hash(myBool);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Dummy200ResponseOuterPropInnerProp {\n");
    sb.append("    myBool: ").append(toIndentedString(myBool)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

