/**
 * Some example
 * dummy description
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class ExampleResponse (
  myOnlyProperty: Option[Seq[Boolean]] = None
) extends ApiModel

