/**
 * dummy
 * dummy
 *
 * The version of the OpenAPI document: dummy
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIDummy_200_response_outerProp_innerProp.h
 *
 * 
 */

#ifndef OAIDummy_200_response_outerProp_innerProp_H
#define OAIDummy_200_response_outerProp_innerProp_H

#include <QJsonObject>


#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIDummy_200_response_outerProp_innerProp : public OAIObject {
public:
    OAIDummy_200_response_outerProp_innerProp();
    OAIDummy_200_response_outerProp_innerProp(QString json);
    ~OAIDummy_200_response_outerProp_innerProp() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    bool isMyBool() const;
    void setMyBool(const bool &my_bool);
    bool is_my_bool_Set() const;
    bool is_my_bool_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    bool my_bool;
    bool m_my_bool_isSet;
    bool m_my_bool_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIDummy_200_response_outerProp_innerProp)

#endif // OAIDummy_200_response_outerProp_innerProp_H
