/**
 * dummy
 * dummy
 *
 * The version of the OpenAPI document: dumy
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIExampleResponse.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIExampleResponse::OAIExampleResponse(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIExampleResponse::OAIExampleResponse() {
    this->initializeModel();
}

OAIExampleResponse::~OAIExampleResponse() {}

void OAIExampleResponse::initializeModel() {

    m_my_only_property_isSet = false;
    m_my_only_property_isValid = false;
}

void OAIExampleResponse::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIExampleResponse::fromJsonObject(QJsonObject json) {

    m_my_only_property_isValid = ::OpenAPI::fromJsonValue(my_only_property, json[QString("myOnlyProperty")]);
    m_my_only_property_isSet = !json[QString("myOnlyProperty")].isNull() && m_my_only_property_isValid;
}

QString OAIExampleResponse::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIExampleResponse::asJsonObject() const {
    QJsonObject obj;
    if (my_only_property.size() > 0) {
        obj.insert(QString("myOnlyProperty"), ::OpenAPI::toJsonValue(my_only_property));
    }
    return obj;
}

QSet<double> OAIExampleResponse::getMyOnlyProperty() const {
    return my_only_property;
}
void OAIExampleResponse::setMyOnlyProperty(const QSet<double> &my_only_property) {
    this->my_only_property = my_only_property;
    this->m_my_only_property_isSet = true;
}

bool OAIExampleResponse::is_my_only_property_Set() const{
    return m_my_only_property_isSet;
}

bool OAIExampleResponse::is_my_only_property_Valid() const{
    return m_my_only_property_isValid;
}

bool OAIExampleResponse::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (my_only_property.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIExampleResponse::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
