/*
 * Some example
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ExampleResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExampleResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ExampleResponse
        //private ExampleResponse instance;

        public ExampleResponseTests()
        {
            // TODO uncomment below to create an instance of ExampleResponse
            //instance = new ExampleResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExampleResponse
        /// </summary>
        [Test]
        public void ExampleResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ExampleResponse
            //Assert.IsType<ExampleResponse>(instance);
        }

        /// <summary>
        /// Test the property 'MyOnlyProperty'
        /// </summary>
        [Test]
        public void MyOnlyPropertyTest()
        {
            // TODO unit test for the property 'MyOnlyProperty'
        }
    }
}
