openapi: 3.0.0
info:
  description: dummy
  title: dummy
  version: dummy
servers:
- url: /
paths:
  /example/someMethod:
    get:
      description: dummy
      operationId: dummy
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ExampleResponse'
          description: dummy
        "201":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Node'
          description: dummy
      x-openapi-router-controller: openapi_server.controllers.default_controller
components:
  schemas:
    ExampleResponse:
      description: dummy
      example:
        myOnlyProperty:
          myOnlyProperty2: null
      properties:
        myOnlyProperty:
          $ref: '#/components/schemas/OtherObject'
      title: ExampleResponse
      type: object
    OtherObject:
      description: dummy
      example:
        myOnlyProperty2: null
      properties:
        myOnlyProperty2:
          $ref: '#/components/schemas/ExampleResponse'
      title: OtherObject
      type: object
    Node:
      description: dummy
      properties:
        left:
          $ref: '#/components/schemas/Node'
        right:
          $ref: '#/components/schemas/Node'
      title: Node
      type: object
