/*
 * dummy
 *
 * dummy
 *
 * The version of the OpenAPI document: dumy
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// dummy
    /// </summary>
    [DataContract(Name = "ExampleResponse")]
    public partial class ExampleResponse : IEquatable<ExampleResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExampleResponse" /> class.
        /// </summary>
        /// <param name="myOnlyProperty">myOnlyProperty.</param>
        public ExampleResponse(List<decimal> myOnlyProperty = default(List<decimal>))
        {
            this.MyOnlyProperty = myOnlyProperty;
        }

        /// <summary>
        /// Gets or Sets MyOnlyProperty
        /// </summary>
        [DataMember(Name = "myOnlyProperty", EmitDefaultValue = false)]
        public List<decimal> MyOnlyProperty { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ExampleResponse {\n");
            sb.Append("  MyOnlyProperty: ").Append(MyOnlyProperty).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ExampleResponse);
        }

        /// <summary>
        /// Returns true if ExampleResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of ExampleResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ExampleResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.MyOnlyProperty == input.MyOnlyProperty ||
                    this.MyOnlyProperty != null &&
                    input.MyOnlyProperty != null &&
                    this.MyOnlyProperty.SequenceEqual(input.MyOnlyProperty)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.MyOnlyProperty != null)
                {
                    hashCode = (hashCode * 59) + this.MyOnlyProperty.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
