/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.0.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import springfox.documentation.annotations.ApiIgnore;
import org.openapitools.model.ExampleResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import org.springframework.http.codec.multipart.Part;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Api(value = "example", description = "the example API")
public interface ExampleApi {

    default ExampleApiDelegate getDelegate() {
        return new ExampleApiDelegate() {};
    }

    /**
     * GET /example/someMethod
     * 
     *
     * @return  (status code 200)
     */
    @ApiOperation(
        value = "",
        nickname = "exampleSomeMethodGet",
        notes = "",
        response = ExampleResponse.class
    )
    @ApiResponses({
        @ApiResponse(code = 200, message = "", response = ExampleResponse.class)
    })
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/example/someMethod",
        produces = { "*/*" }
    )
    default Mono<ResponseEntity<ExampleResponse>> exampleSomeMethodGet(
        @ApiIgnore final ServerWebExchange exchange
    ) {
        return getDelegate().exampleSomeMethodGet(exchange);
    }

}
