/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Dummy200ResponseOuterPropInnerProp

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.io.Serializable

/**
 * 
 *
 * @param innerProp 
 */


data class Dummy200ResponseOuterProp (

    @Json(name = "innerProp")
    val innerProp: Dummy200ResponseOuterPropInnerProp? = null

) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

