/*
 * dummy
 * dummy
 *
 * The version of the OpenAPI document: dummy
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.client.model.Dummy200ResponseOuterProp;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for Dummy200Response
 */
public class Dummy200ResponseTest {
    private final Dummy200Response model = new Dummy200Response();

    /**
     * Model tests for Dummy200Response
     */
    @Test
    public void testDummy200Response() {
        // TODO: test Dummy200Response
    }

    /**
     * Test the property 'outerProp'
     */
    @Test
    public void outerPropTest() {
        // TODO: test outerProp
    }

}
