/* tslint:disable */
/* eslint-disable */
/**
 * dummy
 * dummy
 *
 * The version of the OpenAPI document: dummy
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Dummy200ResponseOuterPropInnerProp } from './dummy200-response-outer-prop-inner-prop';

/**
 * 
 * @export
 * @interface Dummy200ResponseOuterProp
 */
export interface Dummy200ResponseOuterProp {
    /**
     * 
     * @type {Dummy200ResponseOuterPropInnerProp}
     * @memberof Dummy200ResponseOuterProp
     */
    'innerProp'?: Dummy200ResponseOuterPropInnerProp;
}

