/**
 * dummy
 * dummy
 *
 * The version of the OpenAPI document: dummy
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Observable } from 'rxjs/Observable';

import { map } from 'rxjs/operators';
import IHttpClient from '../IHttpClient';
import { inject, injectable } from 'inversify';
import { IAPIConfiguration } from '../IAPIConfiguration';
import { Headers } from '../Headers';
import HttpResponse from '../HttpResponse';

import { Dummy200Response } from '../model/dummy200Response';

import { COLLECTION_FORMATS }  from '../variables';



@injectable()
export class DefaultService {
    private basePath: string = 'http://localhost';

    constructor(@inject('IApiHttpClient') private httpClient: IHttpClient,
        @inject('IAPIConfiguration') private APIConfiguration: IAPIConfiguration ) {
        if(this.APIConfiguration.basePath)
            this.basePath = this.APIConfiguration.basePath;
    }

    /**
     * 
     * dummy
     
     */
    public dummy(observe?: 'body', headers?: Headers): Observable<Dummy200Response>;
    public dummy(observe?: 'response', headers?: Headers): Observable<HttpResponse<Dummy200Response>>;
    public dummy(observe: any = 'body', headers: Headers = {}): Observable<any> {
        headers['Accept'] = '*/*';

        const response: Observable<HttpResponse<Dummy200Response>> = this.httpClient.get(`${this.basePath}/example/someMethod`, headers);
        if (observe === 'body') {
               return response.pipe(
                   map((httpResponse: HttpResponse) => <Dummy200Response>(httpResponse.response))
               );
        }
        return response;
    }

}
