/**
* dummy
* dummy
*
* The version of the OpenAPI document: dummy
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.database.models

import org.ktorm.dsl.*
import org.ktorm.schema.*
import org.ktorm.database.Database
import org.openapitools.client.models.*


/**
 * dummy
 * @param emptyString 
 * @param numberString 
 * @param boolString 
 * @param nullString 
 * @param aBool 
 * @param zero 
 */
object ExampleResponses : BaseTable<ExampleResponse>("ExampleResponse") {
    val emptyString = text("emptyString") /* null */
    val numberString = text("numberString") /* null */
    val boolString = text("boolString") /* null */
    val nullString = text("nullString") /* null */
    val aBool = boolean("aBool") /* null */
    val zero = int("zero") /* null */

    /**
     * Create an entity of type ExampleResponse from the model
     */
    override fun doCreateEntity(row: QueryRowSet, withReferences: Boolean) = ExampleResponse(
        emptyString = row[emptyString] ?: "" /* kotlin.String? */,
        numberString = row[numberString] ?: "42" /* kotlin.String? */,
        boolString = row[boolString] ?: "false" /* kotlin.String? */,
        nullString = row[nullString] ?: "null" /* kotlin.String? */,
        aBool = row[aBool] ?: false /* kotlin.Boolean? */,
        zero = row[zero] ?: 0 /* kotlin.Int? */
    )

    /**
    * Assign all the columns from the entity of type ExampleResponse to the DML expression.
    *
    * Usage:
    *
    * ```kotlin
    * let entity = ExampleResponse()
    * database.update(ExampleResponses, {
    *     assignFrom(entity)
    * })
    * ```
    * @return the builder with the columns for the update or insert.
    */
    fun AssignmentsBuilder.assignFrom(entity: ExampleResponse) {
        this.apply {
            set(ExampleResponses.emptyString, entity.emptyString)
            set(ExampleResponses.numberString, entity.numberString)
            set(ExampleResponses.boolString, entity.boolString)
            set(ExampleResponses.nullString, entity.nullString)
            set(ExampleResponses.aBool, entity.aBool)
            set(ExampleResponses.zero, entity.zero)
        }
    }

}


