/**
* dummy
* dummy
*
* The version of the OpenAPI document: dummy
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.database.models

import org.ktorm.dsl.*
import org.ktorm.schema.*
import org.ktorm.database.Database
import org.openapitools.client.models.*


/**
 * dummy
 * @param left 
 * @param right 
 */
object Nodes : BaseTable<Node>("Node") {
    val left = long("left") /* null */
    val right = long("right") /* null */

    /**
     * Create an entity of type Node from the model
     */
    override fun doCreateEntity(row: QueryRowSet, withReferences: Boolean) = Node(
        left = Nodes.createEntity(row, withReferences) /* Node? */,
        right = Nodes.createEntity(row, withReferences) /* Node? */
    )

    /**
    * Assign all the columns from the entity of type Node to the DML expression.
    *
    * Usage:
    *
    * ```kotlin
    * let entity = Node()
    * database.update(Nodes, {
    *     assignFrom(entity)
    * })
    * ```
    * @return the builder with the columns for the update or insert.
    */
    fun AssignmentsBuilder.assignFrom(entity: Node) {
        this.apply {
            set(Nodes.left, entity.left)
            set(Nodes.right, entity.right)
        }
    }

}


