// tslint:disable
/**
 * dummy
 * dummy
 *
 * The version of the OpenAPI document: dummy
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface Dummy200ResponseOuterPropInnerProp
 */
export interface Dummy200ResponseOuterPropInnerProp {
    /**
     * @type {boolean}
     * @memberof Dummy200ResponseOuterPropInnerProp
     */
    myBool?: boolean;
}
