/*
 * dummy
 *
 * dummy
 *
 * The version of the OpenAPI document: dummy
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;
using OpenAPIClientUtils = Org.OpenAPITools.Client.ClientUtils;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Dummy200Response
    /// </summary>
    [DataContract(Name = "dummy_200_response")]
    public partial class Dummy200Response : IEquatable<Dummy200Response>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Dummy200Response" /> class.
        /// </summary>
        /// <param name="outerProp">outerProp.</param>
        public Dummy200Response(Dummy200ResponseOuterProp outerProp = default(Dummy200ResponseOuterProp))
        {
            this._OuterProp = outerProp;
            if (this.OuterProp != null)
            {
                this._flagOuterProp = true;
            }
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Gets or Sets OuterProp
        /// </summary>
        [DataMember(Name = "outerProp", EmitDefaultValue = false)]
        public Dummy200ResponseOuterProp OuterProp
        {
            get{ return _OuterProp;}
            set
            {
                _OuterProp = value;
                _flagOuterProp = true;
            }
        }
        private Dummy200ResponseOuterProp _OuterProp;
        private bool _flagOuterProp;

        /// <summary>
        /// Returns false as OuterProp should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeOuterProp()
        {
            return _flagOuterProp;
        }
        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Dummy200Response {\n");
            sb.Append("  OuterProp: ").Append(OuterProp).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return OpenAPIClientUtils.compareLogic.Compare(this, input as Dummy200Response).AreEqual;
        }

        /// <summary>
        /// Returns true if Dummy200Response instances are equal
        /// </summary>
        /// <param name="input">Instance of Dummy200Response to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Dummy200Response input)
        {
            return OpenAPIClientUtils.compareLogic.Compare(this, input).AreEqual;
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.OuterProp != null)
                {
                    hashCode = (hashCode * 59) + this.OuterProp.GetHashCode();
                }
                if (this.AdditionalProperties != null)
                {
                    hashCode = (hashCode * 59) + this.AdditionalProperties.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
