name: Maven plugin tests

on:
  push:
    paths:
      - modules/openapi-generator-maven-plugin/**
  pull_request:
    paths:
      - modules/openapi-generator-maven-plugin/**

jobs:
  test:
    name: Maven plugin tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Run tests
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
        run: |
          ./mvnw clean install -DskipTests -Dmaven.javadoc.skip=true
          ./mvnw clean compile -f modules/openapi-generator-maven-plugin/examples/java-client.xml
          ./mvnw clean install -f modules/openapi-generator-maven-plugin/examples/multi-module/sample-external-ref-schema/pom.xml
          ./mvnw clean compile -f modules/openapi-generator-maven-plugin/examples/multi-module/pom.xml
          ./mvnw clean compile -f modules/openapi-generator-maven-plugin/examples/kotlin.xml
          ./mvnw clean compile -f modules/openapi-generator-maven-plugin/examples/spring.xml
