/*
 * dummy
 * dummy
 *
 * The version of the OpenAPI document: dumy
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ExampleResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * 
     *
     * dummy
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void dummyTest() throws ApiException {
        ExampleResponse response = 
        api.dummy();
        
        // TODO: test validations
    }
    
}
