/*
 * dummy
 *
 * dummy
 *
 * API version: dummy
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package petstoreserver


import (
	"encoding/json"
)



type Dummy200ResponseOuterProp struct {

	InnerProp Dummy200ResponseOuterPropInnerProp `json:"innerProp,omitempty"`
}

// UnmarshalJSON sets *m to a copy of data while respecting defaults if specified.
func (m *Dummy200ResponseOuterProp) UnmarshalJSON(data []byte) error {

	type Alias Dummy200ResponseOuterProp // To avoid infinite recursion
    return json.Unmarshal(data, (*Alias)(m))
}

// AssertDummy200ResponseOuterPropRequired checks if the required fields are not zero-ed
func AssertDummy200ResponseOuterPropRequired(obj Dummy200ResponseOuterProp) error {
	if err := AssertDummy200ResponseOuterPropInnerPropRequired(obj.InnerProp); err != nil {
		return err
	}
	return nil
}

// AssertDummy200ResponseOuterPropConstraints checks if the values respects the defined constraints
func AssertDummy200ResponseOuterPropConstraints(obj Dummy200ResponseOuterProp) error {
	return nil
}
